### ISSUE TITLE
Stripe 18.4.

### ISSUE THREAD

**Issue by michzio** [stripe/stripe-ios#1532] opened 2020-03-25 11:04 UTC
I have such error in new Xcode version 11.4

`Incompatible block pointer types sending '__strong STPAPIResponseBlock _Nonnull' (aka 'void (^__strong)(__strong ResponseType, NSHTTPURLResponse *__strong, NSError *__strong)') to parameter of type 'void (^)(STPSource *__strong, NSHTTPURLResponse *__strong, NSError *__strong)'`

**Comment by michzio** [comment] 2020-03-25 11:16
It is here in this code snippet (I removed currently this completion block passing as argument

- (NSURLSessionDataTask *)retrieveSourceWithId:(NSString *)identifier clientSecret:(NSString *)secret responseCompletion:(STPAPIResponseBlock)completion {
    NSString *endpoint = [NSString stringWithFormat:@"%@/%@", APIEndpointSources, identifier];
    NSDictionary *parameters = @{@"client_secret": secret};
    
    return [STPAPIRequest<STPSource *> getWithAPIClient:self endpoint:endpoint parameters:parameters deserializer:[STPSource new] completion:^(STPSource *object, NSHTTPURLResponse *response, NSError *error) {
        
    }];
    
}

**Comment by DenisVK** [comment] 2020-03-25 15:29
Having the same issue.

**Comment by reececomo** [comment] 2020-03-25 18:01
👍 I have the same issue

<img width="279" alt="Screen Shot 2020-03-26 at 2 00 37 am" src="https://user-images.githubusercontent.com/7390781/77569730-998e9780-6f05-11ea-90c6-5c2089adfac0.png">

**Comment by davidme-stripe** [comment] 2020-03-25 18:13
Hey all, this is fixed in Stripe v19.0.1. Migration from v18.4 shouldn't require any changes for most users. Instructions for updating Connect platforms are available in [MIGRATING.md](https://github.com/stripe/stripe-ios/blob/master/MIGRATING.md). We'll also have fixes available soon for Stripe v14, v15, and v17.

**Comment by Igorsnaki** [comment] 2020-03-25 19:05
@davidme-stripe Thank you for response. 

"We'll also have fixes available soon for Stripe v14, v15, and v17."

Does it mean that you will release new version v.15.x.x which will contain fix for Xcode v.11.4

**Comment by davidme-stripe** [comment] 2020-03-25 19:20
We've released [v14.0.1](https://github.com/stripe/stripe-ios/releases/tag/v14.0.1), [v15.0.2](https://github.com/stripe/stripe-ios/releases/tag/v15.0.2), and [v17.0.3](https://github.com/stripe/stripe-ios/releases/tag/v17.0.3) to Cocoapods with fixes for this issue.

**Comment by davidme-stripe** [comment] 2020-03-25 19:24
Going to close this out as a dupe of #1525, feel free to continue the discussion in there.

**Closed by davidme-stripe** 2020-03-25 19:24 UTC
