### ISSUE TITLE
Release supporting Swift 2.3

### ISSUE THREAD

**Issue by irskep** [stripe/stripe-ios#456] opened 2016-09-21 00:03 UTC
## Summary

You never released a version of this framework that works with Swift 2.3, only 2.2 and 3.0. Anyone who hasn't had time to migrate to Swift 3 has to use a fork that contains the necessary xcodeproj changes.

## Installation method

Carthage

## SDK version

This applies to any version. I would be happy if you did a single "Swift 2.3 version", 8.0.6.1 or something. Any git tag with a working version would solve my problem.

**Comment by irskep** [comment] 2016-09-21 00:12
FWIW, it would be sufficient to cherry-pick this commit and make a git tag. https://github.com/irskep/stripe-ios/commit/f1274bb9b70948795d1e7e1f66e342f12238cd46

**Comment by bdorfman** [comment] 2016-09-21 00:18
The framework should work with any version of Swift, as it is written in Objective-C. The only thing that requires Swift 3 is our example app. Are you having trouble integrating our framework with your Swift 2.3 app?

**Comment by irskep** [comment] 2016-09-21 00:19
Interesting. Carthage must be trying to build something it shouldn't.

**Comment by irskep** [comment] 2016-09-21 00:25
Since your example schemes are marked Shared in Xcode, Carthage tries to build them as dependencies, and then fails due to the Swift version mismatch. Marking them un-shared should fix the issue for all Swift+Carthage users.

I'm not sure what the "shared" tradeoff is for projects like this. Up to you I guess.

![screenshot 2016-09-20 17 25 08](https://cloud.githubusercontent.com/assets/40085/18693539/41b2ff5c-7f57-11e6-9e1a-178d27b3a3b9.png)

**Comment by bdorfman** [comment] 2016-09-21 00:28
These schemes are intentionally shared. Non-shared schemes are stored in a folder specific to the logged in user and thus are not committed to git. We want these schemes to be available to anyone who clones our project so that they can build the example apps, tests, and static version of the framework.

If Carthage is building shared schemes that are not dynamic frameworks, that seems like a Carthage bug and I recommend you open an issue on them (or possibly check that you have the latest version of Carthage installed on your machine).

**Closed by bdorfman** 2016-09-21 00:28 UTC

**Comment by irskep** [comment] 2016-09-21 00:30
I don't think that's factually correct. If you look at my screenshot, there are two schemes that aren't shared, yet I managed to get them from Git. I didn't create them myself.

In any case, the usage of shared schemes is a design decision of Carthage, so a bug report won't do anything. I guess I'll just maintain a fork, like a beast of the wilderness.

**Comment by bdorfman** [comment] 2016-09-21 00:33
Xcode automatically generates some schemes for you, which is likely what you are seeing. However any custom schemes or changes to the default generated schemes must be shared for other users to get access to them.

The usage of shared schemes is a design decision of Carthage, but I do not believe building non-dynamic-framework schemes is an intended design decision, as it makes no sense for Carthage to try to build things it can't even use, so I still suggest opening an issue with them as this seems like a bug.

**Comment by bdorfman** [comment] 2016-09-21 00:34
Additionally, we attach pre built dynamic frameworks to all our releases, which Carthage should be able to download and use without having to clone and build our repo, unless you disabled that functionality.

**Comment by irskep** [comment] 2016-09-21 00:38
I'll do some more digging. Thanks for taking the time to explain, I really appreciate it!

I do not use the `--no-use-binaries` flag. Maybe there's some quirk in their Swift support that's overzealous about finding code to build.

**Comment by bdorfman** [comment] 2016-09-21 00:42
No problem, sorry you are having troubles getting the framework integrated. As a stop gap you can probably just remove us from your Cartfile and then download our dynamic framework manually and place it in the Carthage build directory. I have found several comments on their Github issues from core developers saying that Carthage only builds dynamic framework schemes, so it sounds like there is a regression in the version you have installed. Let us know if there is anything else we can do to help!

**Comment by jflinter** [comment] 2016-09-21 02:35
@irskep - I'm going to try and reproduce this on our end. What version of Carthage are you using (run `carthage version`), and will you paste the contents of your `Cartfile` (or at least the parts pertaining to Stripe)?

I'm still laughing at "like a beast of the wilderness", by the way.

**Comment by irskep** [comment] 2016-09-21 16:21
It looks like the cause of this issue is PEBKAC.

I've been working on getting our app to build on Xcode 8, which involved updating a bunch of dependencies. At one point, `stripe-ios` wasn't working, and doing the fork/Swift upgrade dance seemed to fix it. But now, with all the dust settled with some configuration having changed, I reverted our `stripe-ios` dependency version to what it was before (6.x) and it's working fine.

There might still be a problem with Carthage building things it shouldn't. We use Realm too, and it's also building their example targets. So this is at least not specific to `stripe-ios`. I'm running 0.18, the very latest version of Carthage.
