### ISSUE TITLE
[BUG]  paymentOptionsViewControllerFooterView is not working

### ISSUE THREAD

**Issue by alwayswith** [stripe/stripe-ios#2302] opened 2023-02-20 03:10 UTC
## Summary

When I use the method of presentPaymentOptionsViewController(withNewState:) or pushPaymentOptionsViewController() in STPPaymentContext to present/push the build in payment options UI, I found that the paymentOptionsViewControllerFooterView property is not working.

## Code to reproduce

`STPPaymentContext.swift`

    func presentPaymentOptionsViewController(withNewState state: STPPaymentContextState) {
        assert(
            hostViewController != nil && hostViewController?.viewIfLoaded?.window != nil,
            "hostViewController must not be nil on STPPaymentContext when calling pushPaymentOptionsViewController on it. Next time, set the hostViewController property first!"
        )
        if self.state == STPPaymentContextState.none {
            self.state = state
            let paymentOptionsViewController = STPPaymentOptionsViewController(paymentContext: self) //  onSuccess is invoked, paymentOptionsViewControllerFooterView is nil
            self.paymentOptionsViewController = paymentOptionsViewController
            paymentOptionsViewController.prefilledInformation = prefilledInformation
            paymentOptionsViewController.defaultPaymentMethod = defaultPaymentMethod
            paymentOptionsViewController.paymentOptionsViewControllerFooterView =
                paymentOptionsViewControllerFooterView  // assign property after onSuccess
            paymentOptionsViewController.addCardViewControllerFooterView =
                addCardViewControllerFooterView
            paymentOptionsViewController.navigationItem.largeTitleDisplayMode =
                largeTitleDisplayMode

            let navigationController = UINavigationController(
                rootViewController: paymentOptionsViewController)
            navigationController.navigationBar.stp_theme = theme
            navigationController.navigationBar.prefersLargeTitles = true
            navigationController.modalPresentationStyle = modalPresentationStyle
            hostViewController?.present(
                navigationController,
                animated: transitionAnimationsEnabled())
        }
    }

`STPPaymentOptionsViewController.swift`

// strongSelf.paymentOptionsViewControllerFooterView is  always nil, because you assign  the property after the onSuccess callback invoked
                if strongSelf.paymentOptionsViewControllerFooterView != nil { 
                    payMethodsInternal?.customFooterView =
                        strongSelf.paymentOptionsViewControllerFooterView
                }

## iOS version
14.5

## Installation method
CocoaPods 

## SDK version
22.8.4

**Comment by wooj-stripe** [comment] 2023-02-22 21:51
Hi @alwayswith ,

Thank you for reaching out with regards to this bug.  I have confirmed that this does seem to be a bug.  I can reproduce this in our basic integration sample application with the following steps:
1.  Build and run basic integration app in our repo
2. Add jeans or other items to your basket
3. Click "buy now"
4. Wait for the "Pay now" row to finish spinning (e.g. network call completes)
5. Click on the payment method to invoke `pushPaymentOptionsViewController` (or change the code to call `presentPaymentOptionsViewController`)

Using the steps above, I observe that the bottom footer does not appear on the paymentOptionsViewController, and the expected behavior is that the bottom footer does show. As you have explained, it is because the `promise` is called before setting `payMethodsInternal?.customFooterView`.  The promise corresponds to the call to `apiAdapter.retrieveCustomer` in `STPPaymentContext::retryLoading()`. So it seems that we have a race condition between `presentPaymentOptionsViewController` (and `pushPaymentOptionsViewController`) with our network call.

I'm [proposing a fix](https://github.com/stripe/stripe-ios/pull/2314), and will update this issue as I get additional information.

**Comment by wooj-stripe** [comment] 2023-02-27 18:10
Hi @alwayswith -
Thanks again for reporting this issue. I've pushed in the code into our master branch, and should be released in our next version. 

I am optimistically closing this ticket, but feel free to reach out if you have any questions or this does not address the problem you initially described.

**Closed by wooj-stripe** 2023-02-27 18:10 UTC
Labels: kind:bug
