### ISSUE TITLE
STPPaymentHandler confirmPayment localizedDescription message is unhelpful when STPPaymentHandlerActionStatusFailed

### ISSUE THREAD

**Issue by carlosanjos** [stripe/stripe-ios#1360] opened 2019-09-09 14:04 UTC
SDK version: Stripe 16.0.7
iOS version: 12.3.1

Sometimes, a PaymentIntent when confirmed returns a `STPPaymentHandlerActionStatus` 
status `STPPaymentHandlerActionStatusFailed` and the error message is not helpful, the error code is 0. The expanded error message is not very helpful either
` Error Domain=STPPaymentHandlerErrorDomain Code=0 "There was an unexpected error -- try again in a few seconds" UserInfo={com.stripe.lib:ErrorMessageKey=The SDK doesn't recognize the PaymentIntent action type., NSLocalizedDescription=There was an unexpected error -- try again in a few seconds, STPIntentActionUseStripeSDK=<STPIntentActionUseStripeSDK: 0x281b856e0; directoryServer = (null); directoryServerID = (null); directoryServerKeyID = (null); serverTransactionID = (null); directoryServerCertificate = (null); rootCertificateStrings = (null); threeDS2SourceID = (null); type = stripe_3ds2_challenge; redirectURL = (null)>}`

This PaymentIntent is attached to the payment card **4000 0000 0000 3220**
The snippet below reproduces the error.

``` Objective-C
[[STPAPIClient sharedClient] retrievePaymentIntentWithClientSecret:@"pi_1FFitPGTjGfaNp3TI35BSznz_secret_QVNJITKrn75Cp4EgslWnO7HF9" completion:^(STPPaymentIntent * _Nullable paymentIntent, NSError * _Nullable error) {
        
        STPPaymentIntentParams *paymentIntentParams = [[STPPaymentIntentParams alloc] initWithClientSecret:paymentIntent.clientSecret];
        paymentIntentParams.paymentMethodId = paymentIntent.paymentMethodId;
        
        [[STPPaymentHandler sharedHandler] confirmPayment:paymentIntentParams withAuthenticationContext:self completion:^(STPPaymentHandlerActionStatus status, STPPaymentIntent * _Nullable paymentIntent, NSError * _Nullable error) {            
            switch (status) {
                case STPPaymentHandlerActionStatusFailed:
                    NSLog(@"%@", error.localizedDescription);
                    NSLog(@"%@", error.localizedFailureReason);
                    NSLog(@"%@", error);
                    NSLog(@"%ld", (long)error.code);
                    NSLog(@"STPPaymentHandlerActionStatusFailed");
                    break;
                case STPPaymentHandlerActionStatusCanceled:
                    NSLog(@"STPPaymentHandlerActionStatusCanceled");
                    break;
                case STPPaymentHandlerActionStatusSucceeded:
                    NSLog(@"STPPaymentHandlerActionStatusSucceeded");
                    break;
            }
        }];        
    }];
```

**Comment by yuki-stripe** [comment] 2019-09-09 21:54
Hi @carlosanjos,

We're looking into this - I wouldn't expect this error.

**Comment by yuki-stripe** [comment] 2019-09-09 22:43
@carlosanjos 

It looks like the `/confirm` response is sending down `stripe_3ds2_challenge` when the mobile clients expect `stripe_3ds2_fingerprint`.  `stripe_3ds2_challenge` is for the web client.  I'm not sure why this is happening.  Did you start but not complete a web-based PaymentIntent confirmation?

I'd recommend reaching out to [Stripe support](https://support.stripe.com/contact) or the IRC channel (#stripe on freenode).

**Comment by carlosanjos** [comment] 2019-09-10 11:35
The paymentIntent was created in the back-end using the PHP Stripe SDK `"stripe/stripe-php": "^6.40"`

```PHP
$paymentIntent = PaymentIntent::create(
            [
                'customer' => $customer->getReference(),
                'amount' => $invoice->getTotal() * 100,
                'currency' => $invoice->getCurrency()->getName(),
                'payment_method' => $card->getToken(),
                'description' => InvoiceType::getLabelForKey($invoice->getType()) . ' #' . $invoice->getId(),
                'metadata' => [
                    'transactionId' => $transaction->getId()
                ],
            ],
            ['api_key' => $this->getApiKey()]
        );
​
$paymentIntent->confirm([
                'off_session' => true,
            ]);
```

This snippet response is sent to the mobile app, then the `client_secret` is used to confirm the payment as the previously pasted code.

**Comment by yuki-stripe** [comment] 2019-09-10 20:34
@carlosanjos I'd recommend removing the call to `confirm` from your backend and only confirming on the client - is there a particular reason you're doing that?  

I haven't been able to reproduce this on my end, could you provide a set of steps to reproduce this?

**Comment by carlosanjos** [comment] 2019-09-11 17:09
@yuki-stripe 
This [https://pastebin.com/GVb8KDr7](https://pastebin.com/GVb8KDr7) is a PHP application to generate payment intents.
This [https://pastebin.com/tJ3mVFZv](https://pastebin.com/tJ3mVFZv) is an iOS application to confirm the payment intent previously generated.

**Comment by yuki-stripe** [comment] 2019-09-11 20:07
@carlosanjos Thanks, this info was very useful.  I believe this stems from a bug we fixed in `v17.0.0` - if you cancel or otherwise don't complete the authentication flow, re-confirming the same PaymentIntent will result in this error prior to `v17.0.0`.

**Comment by davidme-stripe** [comment] 2019-11-27 00:35
Closing this out. Let us know if you're still seeing this problem in v17.0.0 or later.

**Closed by davidme-stripe** 2019-11-27 00:35 UTC
Labels: triaged

**Comment by cythb** [comment] 2020-10-12 08:33
I had a similar problem with the 19.2 SDK.
The first time `STPPaymentHandler.shared().handleNextAction` killed and restarted the application when it popped up for 3DS verification.
Do `STPPaymentHandler.shared().handleNextAction` again and an error is returned.

```
error

▿ Optional<Error>
  - some : Error Domain=STPPaymentHandlerErrorDomain Code=0 "There was an unexpected error -- try again in a few seconds" UserInfo={com.stripe.lib:ErrorMessageKey=The SDK doesn't recognize the PaymentIntent action type., NSLocalizedDescription=There was an unexpected error -- try again in a few seconds, STPIntentActionUseStripeSDK=<STPIntentActionUseStripeSDK: 0x600002e8b1e0; directoryServer = (null); directoryServerID = (null); directoryServerKeyID = (null); serverTransactionID = (null); directoryServerCertificate = (null); rootCertificateStrings = (null); threeDSSourceID = (null); type = stripe_3ds2_challenge; redirectURL = (null)>}
```

` /v1/payment_intents/` first response:
```
...
	"next_action": {
		"type": "use_stripe_sdk",
		"use_stripe_sdk": {
			"type": "stripe_3ds2_fingerprint",
...
```

Second return
```
...
	"next_action": {
		"type": "use_stripe_sdk",
		"use_stripe_sdk": {
			"type": "stripe_3ds2_challenge",
...
```
