### ISSUE TITLE
Customer is unable to select Apple Pay as payment method after they've added cards? (Obj-c)

### ISSUE THREAD

**Issue by brittanyblair** [stripe/stripe-ios#1137] opened 2019-02-17 21:26 UTC
Hi Stripe, 

I've integrated the Stripe iOS SDK into my app, and everything works as it should... EXCEPT, once my customer has added a new card to their profile (customer id), they are then unable to select Apple Pay as their method of preferred payment again? If any more than 1 card is present, users are unable to re-select Apple Pay.

Is this normal?

**Comment by aliriaz-stripe** [comment] 2019-02-19 16:43
Hi Brittany,
That is not expected behavior. I ran a quick test on my end, I'm not experiencing the issue you describe, i.e. I'm able to select Apple Pay after adding a new card to the Stripe Customer.

This seems like an integration issue so we'll be able to assist you better if you write in to `https://support.stripe.com/`.

When you write in, it would be helpful if you provide details on: 
- Steps to reproduce what you are seeing
- What integration path you are using in your project (i.e. whether Standard or Custom Integration)
- Code snippets (via github gist or pastebin) of how you are setting up the Stripe components in your application
- Screenshots or a screen recording of what happens when you follow the repro steps

Since this isn't an SDK issue, I'll close this here.
Looking forward to hearing from you on the support channels!

**Closed by aliriaz-stripe** 2019-02-19 16:43 UTC
