### ISSUE TITLE
3D Secure v1 payment always fail after a first failure

### ISSUE THREAD

**Issue by mhausherr** [stripe/stripe-ios#1397] opened 2019-09-30 09:04 UTC
## Summary
After a first 3d secure v1 failed payment no more payments are possible.
Get an error `STPPaymentHandlerErrorDomain code: 6` 
localizedDescription `There was an unexpected error -- try again in a few second`

## Code to reproduce
```
let paymentIntentParams = STPPaymentIntentParams(clientSecret: clientSecret)
paymentIntentParams.returnURL = returnURL
STPPaymentHandler.shared().confirmPayment(withParams: paymentIntentParams, authenticationContext: self)
```
Confirm a payment, a web 3d-secure web page is shown.
Choose failure.
Confirm an other payment with same amount (but with new clientSecret), got the error.
Kill the app and confirm another payment with same amount, no error, the web page is shown.

## What I try as a workaround
Avoid to use `STPAPIClient` singleton `shared()` and create a new client when it's needed. No change.
Avoid to use `STPPaymentHandler` singleton. Not possible as init method is `NS_UNAVAILABLE

## Test card
`4000 0000 0000 3063`
Have the same behavior with production cards

## iOS version
iOS 12.4 / iOS 13.1

## Installation method
Cocoapods

## SDK version
Stripe (17.0.1)

**Comment by davidme-stripe** [comment] 2019-09-30 20:15
Hi @mhausherr, thanks for writing in. I spent some time looking into this, but I can't reproduce the issue on my end.

It looks like you're calling `confirmPayment` while an existing payment is in-flight. Is it possible that you're unintentionally calling a different `STPPaymentHandler` method while waiting for the result of `confirmPayment`?

**Comment by mhausherr** [comment] 2019-10-02 15:26
Hi @david-stripe,
Doing further test on my implementation on back-end code and front-side code because this issue deals with both.

What I really try to do:
if I use
```
let paymentIntentParams = STPPaymentIntentParams(clientSecret: clientSecret)
STPPaymentHandler.shared().confirmPayment(withParams: paymentIntentParams, authenticationContext: self)
```
without returnURL everything works perfectly, but the user is redirected to a page with "Authentication complete, you may now close this window".
To avoid that, and to improve the payment flow, we chose to use the returnUrl to catch the end of the process. 

So:
```
let paymentIntentParams = STPPaymentIntentParams(clientSecret: clientSecret)
paymentIntentParams.returnURL = returnURL
// at the end redirect to an url like my-app://com.myapp/payment/success
STPPaymentHandler.shared().confirmPayment(withParams: paymentIntentParams, authenticationContext: self)
```

As I understand, this call is handled by iOS at a low level and call `func application(_ application: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any]) -> Bool`. The only thing I do in this call (through a notification in notificationCenter) is calling `presentedViewController?.dismiss(animated: true)` in the `STPAuthenticationContext`.

Removing the `my-app://com.myapp/payment/success` redirect on my back-end code, or removing the returnURL param solves my problem.

But is there a way to avoid this "Authentication complete, you may now close this window" in the new flow? It requires a specific user action and might decrease our conversion.

**Comment by davidme-stripe** [comment] 2019-10-03 00:14
It sounds like you're manually dismissing the authentication view controller in your app delegate. I think what you want is to call `Stripe.handleURLCallback()`:

```
    // This method is where you handle URL opens if you are using a native scheme URLs (eg "yourexampleapp://")
    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        let stripeHandled = Stripe.handleURLCallback(with: url)

        if (stripeHandled) {
            return true
        } else {
            // This was not a stripe url, do whatever url handling your app
            // normally does, if any.
        }

        return false
    }

    // This method is where you handle URL opens if you are using univeral link URLs (eg "https://example.com/stripe_ios_callback")
    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        if userActivity.activityType == NSUserActivityTypeBrowsingWeb {
            if let url = userActivity.webpageURL {
                let stripeHandled = Stripe.handleURLCallback(with: url)

                if (stripeHandled) {
                    return true
                } else {
                    // This was not a stripe url, do whatever url handling your app
                    // normally does, if any.
                }
            }
            
        }
        return false
    }
```

**Comment by mhausherr** [comment] 2019-10-03 08:50
Thank you for your help. The code snippet does't seems to achieve what I want.

The return url I set to the STPPaymentIntentParams leads to my own custom url like my-app://3dsecure/success
So `Stripe.handleURLCallback(with: url)` just do nothing and return false. The view controller shown by STPPaymentHandler is not closed. If I close it manually I got the same error like in my first message.

My goal here is to avoid this screen for payment success and for payment failure: 

![Simulator Screen Shot - iPhone Xs - 2019-10-03 at 10 42 25](https://user-images.githubusercontent.com/520890/66112360-fbabb700-e5ca-11e9-8aff-705177862948.png)

Is it a way to avoid that screen in the new 3d secure flow?

**Comment by davidme-stripe** [comment] 2019-10-03 16:54
`Stripe.handleURLCallback(with: url)` should handle closing the authorization view for you as long as the URL exactly matches the URL you're passing into `paymentIntentParams.returnURL` and your app is registered for that scheme.

Can you set a breakpoint when setting the `paymentIntentParams.returnURL = url` and another one where `Stripe.handleURLCallback(with: url)` is called to confirm that the `url` is identical?

**Comment by davidme-stripe** [comment] 2019-11-27 00:42
I'm closing this out, but please let me know if you're still having trouble!

**Closed** 2019-12-18 01:26 UTC
Labels: triaged
