### ISSUE TITLE
Unable to confirm setup intent - (No such setupintent: <private_client_secret>)

### ISSUE THREAD

**Issue by devandanger** [stripe/stripe-ios#1599] opened 2020-07-04 17:12 UTC
## Summary
I'm trying to create a setup intent so I can hold on to card for future usage. (This is all in test btw)
I'm using a node implementation to initiate the creation of this client secret.

```
exports.createStripeSetupIntent = functions.https.onCall(async (data, context) => {
    checkRequestContext(context);
    const uid = getAuthUID(context);
    const stripeCustomerId = await getStripeCustomer(uid);
    const setupIntent = await stripe.setupIntents.create({ customer: stripeCustomerId });
    console.log("Client secret: " + setupIntent.client_secret);
    return Promise.resolve({ clientSecret: setupIntent.client_secret });
});
```

This is consistent with [this web sample](https://github.com/stripe-samples/saving-card-without-payment/blob/7380b78457c71caf29389b93ae6bc47d9c6529a0/server/node/server.js#L41) but not actually the server code in the [native client sample](https://github.com/stripe-samples/mobile-saving-card-without-payment/blob/899385abf73fa67eaac01af98f0df2d080939bda/server/node/server.js#L34).  Based on reading I suspect there needs to be some correlation back to the ```customer.id``` so I figured that the web version was more accurate.

Unfortunately, this code still does not work afterward. Here is the code on the client I'm building off of

```
    @objc func addCard() {
        let cardParams = cardTextField.cardParams
        let paymentMethodParams = Observable.just(STPPaymentMethodParams(card: cardParams, billingDetails: nil, metadata: nil))
        let functions = StripeFunctions()
        let setupIntent = functions.createSetupIntent()
            .map({ (result) -> CreateStripeIntent in
                let decoder = JSONDecoder()
                guard let jsonData = try? JSONSerialization.data(withJSONObject: result.data, options: .fragmentsAllowed) else {
                    fatalError()
                }
                guard let resultObject = try? decoder.decode(CreateStripeIntent.self, from: jsonData) else {
                    fatalError()
                }
                return resultObject
            })
            .map({ (intent) -> String in
                return intent.clientSecret
            })
        
        Observable.combineLatest(paymentMethodParams, setupIntent)
        .map { (paymentMethod, clientSecret) -> STPSetupIntentConfirmParams in
            let setupIntent = STPSetupIntentConfirmParams(clientSecret: clientSecret)
            setupIntent.paymentMethodParams = paymentMethod
            return setupIntent
        }.subscribe(onNext: { [unowned self] (setupIntent) in
            self.paymentHandler.confirmSetupIntent(withParams: setupIntent, authenticationContext: self) { status, setupIntent, error in
                print("Status: \(status.rawValue) Error: \(error.debugDescription)")
                switch (status) {
                case .failed:
                    break
                case .canceled:
                    // Setup canceled
                    break
                case .succeeded:
                    // Setup succeeded
                    break
                @unknown default:
                    fatalError()
                    break
                }
            }
        }).disposed(by: self.disposeBag)
    }

```

The reactive chains are different then samples but I can confirm that the client secret is being created correctly but still presents the following error.

```
Error: Optional(Error Domain=com.stripe.lib Code=50 "No such setupintent: seti_1H1ErCBaG2uXc9elpGgiVDGs" UserInfo={com.stripe.lib:ErrorMessageKey=No such setupintent: seti_1H1ErCBaG2uXc9elpGgiVDGs, com.stripe.lib:StripeErrorCodeKey=resource_missing, com.stripe.lib:StripeErrorTypeKey=invalid_request_error, com.stripe.lib:ErrorParameterKey=intent, NSLocalizedDescription=No such setupintent: seti_1H1ErCBaG2uXc9elpGgiVDGs})
```

## Code to reproduce
Listed above.

## iOS version
Simulator in Xcode 11.4
## Installation method
Cocoapods 

## SDK version
Stripe 19.3.0

## Other information
I'm using Firebase Cloud Functions for the backends.  I've only verified this under Test, haven't played around with Live mode yet.

**Comment by aliriaz-stripe** [comment] 2020-07-06 15:37
Hi @devandanger, this seems to be an integration issue and not a bug in the iOS SDK, so closing this issue for now, as Github Issues on this repo should be used for bug reports or feature requests only.

However, to unblock your integration, the "No such setupintent" error typically indicates that the Stripe object that is being accessed lives on a different account, meaning the API keys configured might be incorrect.

Could you check the following things for me? 

1) Verify that the secret key and publishable keys you are using, are from the same account? This seems the most likely one to me.

2) Can you log out the value of `clientSecret` before 
```let setupIntent = STPSetupIntentConfirmParams(clientSecret: clientSecret)```
It should be of the format `seti_12345_secret_72468`

3) Please do also share the test mode publishable key you are setting on your iOS app so I can have a look.

Hopefully that unblocks you, please let me know if it does not!
Ali

**Closed by aliriaz-stripe** 2020-07-06 15:37 UTC
