### ISSUE TITLE
[BUG]  'new' is unavailable issue and didcreatetoken sdk fixes conflict

### ISSUE THREAD

**Issue by Dual-Tech** [stripe/stripe-ios#2737] opened 2023-07-14 19:40 UTC
If i use the latest version to fix the "'new' is unavailable: You cannot directly instantiate an STPToken. You should only use one that has been returned from an STPAPIClient callback" issue,I can no longer use the version that supports the didcreatetoken method.

please advise?

**Comment by wooj-stripe** [comment] 2023-07-17 23:02
Hi @Dual-Tech - Thanks for reaching out.

It looks like you' are trying to use deprecated methods `addCardViewController` which is part of the `STPAddCardViewControllerDelegate`.  Is this correct?

These methods have been deprecated as of 16.0.0: https://github.com/stripe/stripe-ios/blob/master/MIGRATING.md#migrating-from-versions--1600 . To use a newer version of the SDK, you will need to migrate your integration from Charges to PaymentIntents: https://stripe.com/docs/payments/payment-intents/migration/charges#read

**Comment by yuki-stripe** [comment] 2023-07-26 23:49
I'm marking this as closed, please re-open if you're still having trouble.

**Comment by Dual-Tech** [comment] 2023-07-26 23:52
There is version 19.0.1 which allows Charges, but it now gives the 'new' is unavailable issue

**Comment by Dual-Tech** [comment] 2023-07-26 23:53
> There is version 19.0.1 which allows Charges, but it now gives the 'new' is unavailable issue

**Comment by yuki-stripe** [comment] 2023-07-28 16:06
@Dual-Tech could you provide example code?

**Comment by Dual-Tech** [comment] 2023-07-28 16:13
> @Dual-Tech could you provide example code?

There isnt code involved, but I can link to the fixes both issues, the fixes now conflict with each other

1.) https://github.com/stripe/stripe-ios/issues/1531

2.) https://github.com/stripe/stripe-ios/issues/2008

**Comment by yuki-stripe** [comment] 2023-07-28 17:40
@Dual-Tech I'm sorry, I'm having trouble understanding what the problem is. I looked at the links you provided but I'm not seeing any mention of the `'new' is unavailable` issue.  

Could you provide an example of the code that's not compiling for you and the version of the SDK you're using?

**Comment by sfriedman-stripe** [comment] 2023-12-24 06:56
Closing due to inactivity

**Closed by sfriedman-stripe** 2023-12-24 06:56 UTC
Labels: kind:bug, triaged
