### ISSUE TITLE
[BUG] Can't build on iOS

### ISSUE THREAD

**Issue by JB-CHAUVIN** [stripe/stripe-ios#1947] opened 2022-03-28 12:52 UTC
Hello,

I have the following error when building on iOS with react native (using the stripe for react-native build : https://github.com/stripe/stripe-react-native) : 

```
❌  /Users/jbchauvin/Library/Developer/Xcode/DerivedData/Docavenue-fjjwzmdmhxmiqkeyzgkogbglnylk/Build/Products/Debug-iphonesimulator/Stripe/Stripe-umbrella.h:13:9: 'STDSAlreadyInitializedException.h' file not found

#import "STDSAlreadyInitializedException.h"
        ^


▸ Compiling ApplePayButtonManager.swift

❌  /Users/jbchauvin/Library/Developer/Xcode/DerivedData/Docavenue-fjjwzmdmhxmiqkeyzgkogbglnylk/Build/Products/Debug-iphonesimulator/Stripe/Stripe-umbrella.h:13:9: 'STDSAlreadyInitializedException.h' file not found

#import "STDSAlreadyInitializedException.h"
        ^


▸ Compiling ApplePayButtonView.swift

❌  /Users/jbchauvin/Library/Developer/Xcode/DerivedData/Docavenue-fjjwzmdmhxmiqkeyzgkogbglnylk/Build/Products/Debug-iphonesimulator/Stripe/Stripe-umbrella.h:13:9: 'STDSAlreadyInitializedException.h' file not found

#import "STDSAlreadyInitializedException.h"
        ^


▸ Compiling CardFormManager.swift

❌  /Users/jbchauvin/Library/Developer/Xcode/DerivedData/Docavenue-fjjwzmdmhxmiqkeyzgkogbglnylk/Build/Products/Debug-iphonesimulator/Stripe/Stripe-umbrella.h:13:9: 'STDSAlreadyInitializedException.h' file not found

#import "STDSAlreadyInitializedException.h"
```

I tried with different dependencies, but same problem... 

1. "@stripe/stripe-react-native": "0.2.4"
2. "@stripe/stripe-react-native": "^0.4.0"

Additional informations 👍 
```    OS: macOS 12.2.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 35.36 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 27, 28, 29, 30, 31, 32
      Build Tools: 29.0.3, 30.0.2, 31.0.0, 32.0.0, 32.1.0
      System Images: android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild```

React native version : 0.68 RC 4

**Comment by charliecruzan-stripe** [comment] 2022-03-29 11:59
duplicate of https://github.com/stripe/stripe-react-native/issues/867

**Closed by charliecruzan-stripe** 2022-03-29 11:59 UTC
Labels: kind:bug
