### ISSUE TITLE
Missing full response when calling Payment Intent's confirm endpoint

### ISSUE THREAD

**Issue by kristiehuang** [stripe/stripe-ios#1616] opened 2020-08-04 20:42 UTC
When calling the payment_intents/confirm endpoint, does not seem to return the full PaymentIntents object? Am specifically missing the payment_intent's `charges` within the response.

The STPPaymentIntent object does not also contain `charges`.

**Comment by aliriaz-stripe** [comment] 2020-08-04 20:48
@kristiehuang  hello!

The `charges` field on PaymentIntent is a secret key only field, i.e. it is not retrievable by publishable key (which is what the mobile SDKs use when calling `/confirm`: https://stripe.com/docs/api/payment_intents/object#payment_intent_object-charges

Could you say more, how are you looking to use the (successful or failed) Charge on the PaymentIntent? 

The PaymentIntent should get you almost everything you need but curious to hear more. 

(Also closing this as this is by design and not an issue with the SDK)

**Closed by aliriaz-stripe** 2020-08-04 20:48 UTC

**Comment by kristiehuang** [comment] 2020-08-04 21:05
Thanks, didn't realize that! API docs show that the paymentIntent's response object contains `charges`. I needed to create a transfer associated with a payment intent, and needed charge ID as the source_transaction parameter to do that.

Ended up using Charges API to get the charge ID associated with payment intent instead

**Comment by aliriaz-stripe** [comment] 2020-08-04 21:20
> API docs show that the paymentIntent's response object contains charges
 
Yes the API ref does! But by default it only shows fields that are secret key viewable only, any publishable key viewable fields are marked as such; for example `status` on PaymentIntent which is publishable key viewable ("_RETRIEVABLE WITH PUBLISHABLE KEY_"): https://stripe.com/docs/api/payment_intents/object#payment_intent_object-status

> I needed to create a transfer associated with a payment intent, and needed charge ID as the source_transaction parameter to do that.

I see, one approach here is you send the PaymentIntent ID to your server, and retrieve it server-side, which gives you the entire PaymentIntent object, with the `charges` array. You could then make the Transfer. Alternatively, the `payment_intent.succeeded` webhook event is another option.
