### ISSUE TITLE
usability issue for user who enters credit card expiration date incorrectly

### ISSUE THREAD

**Issue by zeevvax** [stripe/stripe-ios#162] opened 2015-05-22 19:40 UTC
TO REPRODUCE:
Register a new user, and land on the page with the credit card input fields.
Enter the QA number of 4242 4242 4242 4242 at which point you'll be automatically positioned at the credit card expiration fields.
Enter 9/15 at which point you'll be automatically positioned at the CVC field.
Realizing that your credit card actually expired in 10/15 instead, select the back arrow five times in a row so that the 0 at the beginning of the date field is ready to accept the replacement 1.
EXPECTED BEHAVIOR:
I still want to be positioned on the MM/YY field or have an obvious way to get to it.
ACTUAL BEHAVIOR:
One has to back-arrow/delete the last 2 of the credit card number and then type it in again in order to return to the MM/YY field. Definitely not a good user experience

**Comment by jflinter** [comment] 2015-05-28 19:17
I believe your issue lies with https://github.com/stripe/PaymentKit, not here. This sounds like a duplicate of https://github.com/stripe/PaymentKit/issues/79, so feel free to subscribe to that issue for updates.

**Closed by jflinter** 2015-05-28 19:17 UTC
