### ISSUE TITLE
How to fetch saved Shipping/Billing Address From Apple Pay Wallet via using STPPaymentContext 

### ISSUE THREAD

**Issue by MayankAgarwal04** [stripe/stripe-ios#1412] opened 2019-10-06 21:03 UTC
## Summary
I am using **STPPaymentContext** class for Payment via Apple Pay. I am not able to fetch the saved Billing/Shipping Address from **Apple Pay Wallet** on **Apple Pay Dialog Box** while doing **Payment via Apple Pay**.
Also, please let me know how to set the shipping/billing Address if user has not set the address at the time of adding a card to Apple wallet. 
I need to show the shipping/billing Address on Apple Pay dialog Box in both the case
- User has added Address at the time of adding a card to iOS Wallet.
- User trying to add Address in the application.

Note : I don't want to use **STPShippingAddressViewController** And I am using **STPPaymentContext** 

## Code to reproduce

        let aa = STPUserInformation();
        
        let bb = STPAddress();
        bb.name = "Mayank"        
        
        let cc = STPAddress();
        cc.name = "Mayank"
        
        aa.billingAddress = bb;
        aa.shippingAddress = cc;
        
        self.paymentContext.prefilledInformation = aa;

On Adding the information via using above code Address data is not coming on Apple Pay Dialog Box.

## Installation method
POD

@yuki-stripe @dackerman-stripe  @daved-stripe 
Team, please help me in resolving this issue. I am not able to display shipping/billing Adress on Apple Pay dialog box. Also, I don't want to use stripe AddressView controller. I am using Stripe Native UI and  STPPaymentContext

**Comment by yuki-stripe** [comment] 2019-10-07 17:41
Hi @MayankAgarwal04,

I tried this out, and was able to display a prefilled shipping address on the Apple Pay dialog by setting `prefilledInformation`.  Could you provide more code to reproduce?

**Comment by davidme-stripe** [comment] 2019-12-18 01:28
I'm closing this out, as this seems to be working on our end. Please let me know if you can reproduce the issue!

**Closed by davidme-stripe** 2019-12-18 01:28 UTC
Labels: triaged
