### ISSUE TITLE
STPCustomer has no member decodedObject

### ISSUE THREAD

**Issue by emadd** [stripe/stripe-ios#699] opened 2017-06-13 16:25 UTC
Installed via CocoaPods (10.1.0)

**Comment by bdorfman-stripe** [comment] 2017-06-13 18:06
Hi @emadd,

Can you provide more details on the error you are seeing? Is this an error when compiling our framework, or in your own code? If in our code, a file name and line number would be helpful. If in your code a surrounding code snippet would be great.

Thanks,
Brian

**Comment by emadd** [comment] 2017-06-14 01:20
Looks like whatever version delivered via CocoaPods doesn't conform to the proper protocol.  This is what is exposed to me...

```
import UIKit

//
//  STPCustomer.h
//  Stripe
//
//  Created by Jack Flintermann on 6/9/16.
//  Copyright © 2016 Stripe, Inc. All rights reserved.
//

/**
 *  An `STPCustomer` represents a deserialized Customer object from the Stripe API. You can use `STPCustomerDeserializer` to convert a JSON response from the Stripe API into an `STPCustomer`.
 */
open class STPCustomer : NSObject {

    
    /**
     *  Initialize a customer object with the provided values.
     *
     *  @param stripeID      The ID of the customer, e.g. `cus_abc`
     *  @param defaultSource The default source of the customer, such as an `STPCard` object. Can be nil.
     *  @param sources       All of the customer's payment sources. This might be an empty array.
     *
     *  @return an instance of STPCustomer
     */
    public convenience init(stripeID: String, defaultSource: STPSourceProtocol?, sources: [STPSourceProtocol])

    
    /**
     *  The Stripe ID of the customer, e.g. `cus_1234`
     */
    open var stripeID: String { get }

    
    /**
     *  The default source used to charge the customer.
     */
    open var defaultSource: STPSourceProtocol? { get }

    
    /**
     *  The available payment sources the customer has (this may be an empty array).
     */
    open var sources: [STPSourceProtocol] { get }
}

/**
 Use `STPCustomerDeserializer` to convert a response from the Stripe API into an `STPCustomer` object. `STPCustomerDeserializer` expects the JSON response to be in the exact same format as the Stripe API.
 */
open class STPCustomerDeserializer : NSObject {

    
    /**
     *  Initialize a customer deserializer. The `data`, `urlResponse`, and `error` parameters are intended to be passed from an `NSURLSessionDataTask` callback. After it has been initialized, you can inspect the `error` and `customer` properties to see if the deserialization was successful. If `error` is nil, `customer` will be non-nil (and vice versa).
     *
     *  @param data        An `NSData` object representing encoded JSON for a Customer object
     *  @param urlResponse The URL response obtained from the `NSURLSessionTask`
     *  @param error       Any error that occurred from the URL session task (if this is non-nil, the `error` property will be set to this value after initialization).
     *
     */
    public init(data: Data?, urlResponse: URLResponse?, error: Error?)

    
    /**
     *  Initializes a customer deserializer with a JSON dictionary. This JSON should be in the exact same format as what the Stripe API returns. If it's successfully parsed, the `customer` parameter will be present after initialization; otherwise `error` will be present.
     *
     *  @param json a JSON dictionary.
     *
     */
    public init(jsonResponse json: Any)

    
    /**
     *  If a customer was successfully parsed from the response, it will be set here. Otherwise, this value wil be nil (and the `error` property will explain what went wrong).
     */
    open var customer: STPCustomer? { get }

    
    /**
     *  If the deserializer failed to parse a customer, this property will explain why (and the `customer` property will be nil).
     */
    open var error: Error? { get }
}

```

**Comment by HarveyDoom** [comment] 2017-06-14 01:37
I am also having this exact problem.

**Comment by bdorfman-stripe** [comment] 2017-06-14 16:57
Strange, this sounds like possibly a bug in Xcode when it generates the Swift bridged headers? What version of Xcode and Cocoapods are you running? What is the actual STPCustomer.h file delivered by Cocoapods? The one you copied it in Swift which is generated by Xcode, the actual file will be in Objective-C.

**Comment by bdorfman-stripe** [comment] 2017-06-14 18:30
Ah, actually I think the problem may be some sort of version mismatch on your end. In Stripe SDK v10.1.0, `STPCustomer` does in fact _not_ conform to `STPAPIResponseDecodable` and so correctly does not have a `decodedObjectFromApiResponse:` method.

I'm not sure exactly where you are seeing this error occur, as if you are compiling code all from v10.1.0 nothing should attempt to call that method on STPCustomer. Is it possible you have copied some code from latest master into your app that is causing this issue? You should make sure to always use code only from a released tagged version (and all from the same version), as other commits and branches are considered unstable. 

If you think this is not the issue, it would be helpful if you can give me a code snippet from the location in code you are actually seeing this error so I can help you debug further.

Thanks,
Brian

**Comment by fordc5** [comment] 2017-06-15 00:26
I've been trying to figure out this same issue for the past 3 days. I get the error when I try to build a MyAPIClient file. Specifically, the line that gives the issue is: `if let customer = STPCustomer.decodedObject(fromAPIResponse: result as? [String: AnyObject])`

I have followed all of the protocol for implementing Stripe with Carthage. I added an Objective C Bridging Header as well. I cannot figure out what is causing this error (Type 'STPCustomer' has no member 'decodedObject'). When I run the example from this page it works correctly. My code is essentially the same.

**Comment by bdorfman-stripe** [comment] 2017-06-15 00:48
Sure, happy to help. Where are you getting the `MYAPIClient` file from? 

First of all: I want to be clear that MyAPIClient is intended only for use as part of our example app, and should not be actually used directly in production code in your own app (although it sounds like you are not doing this @fordc5 )

Secondly: It sounds like what is happening is that you have installed Stripe v10.1.0 through Carthage/Cocoapods, and then copied out the MyAPIClient code through some other source (like direct from our github page). If you are just viewing `github.com/stripe/stripe-ios`, that is showing you the code that is the latest commit on the master branch. This is creating a mismatch between what the file is expecting and what you have installed (changes to both STPCustomer and MyAPIClient may have occurred on master since 10.1.0 was released).

If you want to run the example app on 10.1.0, you need to either checkout the `v10.1.0` tag in your clone of the Stripe repo, or download the github zip of the branch at that commit (ie https://github.com/stripe/stripe-ios/archive/v10.1.0.zip ), or view that tag on Github ( https://github.com/stripe/stripe-ios/tree/v10.1.0 )

You should always use code from a tagged official Stripe SDK release that has been posted to the Releases page: https://github.com/stripe/stripe-ios/releases and if you are trying to run our example code, you need to make sure you are looking at the example from the same version of the sdk you have installed.

I hope that helps!
Brian

**Closed by bdorfman-stripe** 2017-06-15 00:48 UTC

**Comment by bdorfman-stripe** [comment] 2017-06-15 00:49
I also want to recommend to anyone having integration problems like this that you write in to support@stripe.com, as they can help you with all sorts of questions or problems you may have getting the Stripe iOS SDK running in your app!

**Comment by fordc5** [comment] 2017-06-19 21:23
Thank you! That clears up a lot. I think I have it figured out now.

**Comment by bdorfman-stripe** [comment] 2017-06-19 21:26
No problem! We will also add a note to our readme directing people to the latest release to alleviate confusion around this :)
