### ISSUE TITLE
STPPaymentCardTextField possibility to focus invisible card info fields with Voice Over

### ISSUE THREAD

**Issue by romanilchyshyndepop** [stripe/stripe-ios#1838] opened 2021-07-07 14:33 UTC
## Summary
User cannot focus next hidden field in case if focused one is expanded and shifts next field out of screen bounds.

Please see the issue reproduced in "UI Examples" project:

https://user-images.githubusercontent.com/72379517/124776969-8c55ba80-df48-11eb-9b85-383d4dde4a5a.MP4

## Code to reproduce
Issue is reproducible in "UI Examples" project as described on the video above.

## iOS version
iOS 14.6 but appliable for older versions as well.

## SDK version
21.6.0 but appliable for older versions as well.

**Comment by romanilchyshyndepop** [comment] 2021-07-07 14:34
Possible solution of the issue https://github.com/stripe/stripe-ios/pull/1837

**Comment by csabol-stripe** [comment] 2021-07-14 21:38
Thanks for highlighting this issue. We actually recently released a replacement for `STPPaymentCardTextField` `STPCardFormView` which was designed to be more accessible. Unfortunately there's not a great solution to this particular issue as once the card number field becomes the first responder, additional fields are hidden and moved off screen. Our example app making the field automatically become the first responder somewhat exasperates this issue because normally all fields would be displayed initially allowing a user to voice over each of them without selecting.

Currently we do allow users to select the next field, which would then expose the hidden fields to voice over.

I'm going to close this one but please let me know if you run into any other accessibility issues with `STPPaymentCardTextField` or `STPCardFormView`

**Closed by csabol-stripe** 2021-07-14 21:38 UTC
Labels: triaged
