### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by AnmolRattan007** [stripe/stripe-ios#1737] opened 2020-12-26 07:31 UTC
Error at STPCardValidationState/possibleBrands/brands = binRanges.map(\.brand)

**Comment by davidme-stripe** [comment] 2021-01-04 17:52
Hello, thanks for filing! This may be a dupe of https://github.com/stripe/stripe-ios/issues/1724, which we're still investigating. Are you using Flutter?

**Comment by AnmolRattan007** [comment] 2021-01-05 12:43
@davidme-stripe I'm using Swift. Also, can I implement Stripe with a lower version like  '20.1.1'?

**Comment by davidme-stripe** [comment] 2021-01-06 23:10
I can't reproduce this, but I made a speculative fix in version [21.2.0](https://github.com/stripe/stripe-ios/releases/tag/21.2.0). Please give it a try!

**Closed** 2021-01-06 23:23 UTC
Labels: triaged
