### ISSUE TITLE
[BUG] paymentCardTextFieldDidEndEditing(_ textField: STPPaymentCardTextField) delegate method not calling in iOS 17

### ISSUE THREAD

**Issue by Harikumar10** [stripe/stripe-ios#2789] opened 2023-07-27 04:51 UTC

**Comment by yuki-stripe** [comment] 2023-07-28 17:42
This looks related or the same as https://github.com/stripe/stripe-ios/issues/2242

**Comment by Harikumar10** [comment] 2023-08-22 07:21
Is there any time line for this issue fix?

**Comment by sfriedman-stripe** [comment] 2023-12-23 23:50
Closing as a dupe of #2242

**Closed by sfriedman-stripe** 2023-12-23 23:50 UTC
Labels: kind:bug, triaged
