### ISSUE TITLE
Cannot conform to STPAddCardViewControllerDelegate since Xcode 8 GM on Swift 3

### ISSUE THREAD

**Issue by ldiqual** [stripe/stripe-ios#437] opened 2016-09-08 01:23 UTC
To make it easier to diagnose your issue, please fill out the following:

## Summary

Since converting my codebase to swift 3 with Xcode 8 GM, I get this error when trying to conform to the `STPAddCardViewControllerDelegate` (Stripe SDK). I'm very surprised by this error because even when stubbing those methods automatically with Xcode I encounter the same error. Types seem to match, no idea what's going on.

    Type 'ViewController' does not conform to protocol 'STPAddCardViewControllerDelegate'

    Protocol requires function 'addCardViewController(_:didCreateToken:completion:)' with type '(STPAddCardViewController, STPToken, STPErrorBlock) -> Void'; do you want to add a stub?
    
    Candidate has non-matching type '(STPAddCardViewController, STPToken, (Error?) -> Void) -> ()'

## Code to reproduce

    extension ViewController: STPAddCardViewControllerDelegate {

        func addCardViewControllerDidCancel(_ addCardViewController: STPAddCardViewController) {
        }
        
        func addCardViewController(_ addCardViewController: STPAddCardViewController, didCreateToken token: STPToken, completion: STPErrorBlock) {
        }
    }

## iOS version

iOS 10, Xcode 8 GM, swift 3

## Installation method

Cocoapods 1.0.1

## SDK version

8.0.4

## Other information

Duplicated this bug report on StackOverflow because it might be due to a bug in the compiler: https://stackoverflow.com/questions/39381210/cannot-conform-to-stpaddcardviewcontrollerdelegate-since-xcode-8-gm-on-swift-3

**Comment by bdorfman** [comment] 2016-09-08 17:06
It sounds like it might just be a compiler or Swift3 conversion issue. Swift3 does not do implicit conversion of types the same was, so you can't use Error and NSError interchangeably. Possibly it is getting confused here somehow because the error type is defined inside the block type. You could try changing your code to read like this

```func addCardViewController(_ addCardViewController: STPAddCardViewController, didCreateToken token: STPToken, completion: (NSError?) -> Void) {
    }```

**Comment by ldiqual** [comment] 2016-09-08 21:26
@bdorfman `STPErrorBlock` is exposed as `(Error?) -> Void` by the swift 3 compiler, so types are matching here. Changing `Error` to `NSError` did not work for me :( 

From the generated header:

```
public typealias STPErrorBlock = (Error?) -> Swift.Void
```

**Comment by ldiqual** [comment] 2016-09-08 21:52
Example project: https://mega.nz/#!1MIFzIgY!7Rap7kzS2UgKuV2w_URpbiNl-X1QJWaLooxRYIX0WEQ

**Comment by bdorfman** [comment] 2016-09-08 21:56
Hmm, this might be a bug with the Xcode 8 GM. This was working fine for me on the last beta, but after upgrading to GM I am getting the same error as you (and also getting similar errors for lots of other classes trying to conform to objc protocols). I would suggest filing a Radar on Apple.

**Comment by ldiqual** [comment] 2016-09-08 22:04
Great suggestion. Since it seems to be a compiler issue, I filed a swift bug here: https://bugs.swift.org/browse/SR-2596

**Comment by bdorfman** [comment] 2016-09-08 22:05
It seems to specifically only be happening for block typedefs that include NSError so I suspect there is some bug in this case when it is trying to convert objc's `NSError` to Swift's `Error` type. I will also file a Radar on both Swift and Xcode.

**Comment by ldiqual** [comment] 2016-09-08 22:09
@bdorfman Got it. Would it be possible to have a PR or a branch that would workaround the issue so I could use it as a dependency in the meantime? Fwiw I'm not providing an error to the completion block because I'm using my own UI element for that, so I don't mine having a `STPVoidBlock` as a temporary workaround. Alternatively, I could patch the Stripe SDK in a `post_install` hook.

**Comment by AliSoftware** [comment] 2016-09-08 22:16
I don't know much of the context here, but reading this function signature:
```
func addCardViewController(_ addCardViewController: STPAddCardViewController, didCreateToken token: STPToken, completion: (NSError?) -> Void) { }
```
It seems to me that maybe the completion block should be marked as `@escaping` (because if you call that a completion block, I'm assuming you're storing that in a property and call it later asynchronously, so that will _escape_ the scope of the function and in the latest Swift 3 closures are non-escaping by default and need to be marked `@escaping` when they are)

That might explain why it consider it different types.

**Comment by bdorfman** [comment] 2016-09-08 22:17
Yes I have tested in an example project, and if you mark the block as `@escaping` it compiles correctly. It seems like the Xcode GM compiler mismatches on this but does not clearly explain why in the error it provides, nor does it correctly provide a stub. But if you mark the blocks as `@escaping` it should compile for you.

**Comment by ldiqual** [comment] 2016-09-08 22:20
@AliSoftware @bdorfman Tested and confirmed the workaround. Thanks a lot! I'll modify the swift bug that I filed to reflect your findings.

**Comment by bdorfman** [comment] 2016-09-08 22:21
Yes, I think the actual bug is Xcode/Swift not providing correct types in the mismatch error, nor providing a correct stub. Thanks @AliSoftware for helping me figure out the problem!

**Comment by AliSoftware** [comment] 2016-09-08 22:21
Yes, to me, that's not a bug in Xcode or the compiler per se, the only Xcode bug there is that the error message is not clear enough (which is totally still worth filing a radar probably even at bugs.swift.org)

But the correct fix in your case is to mark the completion closure in your Swift code as `@escaping`, I mean a completion block is definitely escaping anyway, so **that's not a workaround or something, that's the actual way your completion closure should be annotated anyway** — because by definition completion blocks **are** escaping the function scope and not executed right away but stored for later use

**Closed** 2016-09-08 22:21 UTC
