### ISSUE TITLE
paymentContextDidChange not calling if selects the already selected card

### ISSUE THREAD

**Issue by gowtham1094** [stripe/stripe-ios#1466] opened 2019-12-21 07:37 UTC
## Summary
When calling presentPaymentOptionsViewController() and selects the already selected card then no delegate methods are calling.

## Code to reproduce
           let customerContext = STPCustomerContext(keyProvider: StripePayment.stripeClient!)
            let config = STPPaymentConfiguration.shared()
            config.publishableKey = App.Config.stripeKey
            config.companyName = Constants.appName
            config.requiredBillingAddressFields = .none
            config.requiredShippingAddressFields = .none
            let paymentContext = STPPaymentContext(customerContext: customerContext,configuration : config,theme : .default())
            paymentContext.delegate = self
            paymentContext.hostViewController = delegate?.stripeController
            paymentContext.paymentAmount = 0
            paymentContext.modalPresentationStyle = .fullScreen
            paymentContext.presentPaymentOptionsViewController()

Select the already selected card, no delegate methods are called.  

## iOS version
iOS 13.2.2

## Installation method
through pod installation 

## SDK version

18.3.0

**Comment by davidme-stripe** [comment] 2019-12-23 18:37
Hey @gowtham1094, this is intentional. The `paymentContextDidChange` message will only be sent if the paymentContext's state changes, which it isn't in this case. The next step would be to call `paymentContext.requestPayment()` when the user taps some sort of "Buy" button.

We're open to reconsidering this, though — can you explain your use case a little more? Are you trying to change your UI based on the sheet being dismissed?

**Comment by gowtham1094** [comment] 2019-12-24 16:07
Hey @davidme-stripe , Our application won't charge the user immediately , we need to save the card and start the payment in future. User need to select a card (if there were no card then need to add a new one) before creating an appointment ,so in that case i am not getting any call back if user selects the same card which is already selected. Can you please help me to find a work around for this. I dont want to call requetPayment directly since i am not charging the user immediately.

**Comment by davidme-stripe** [comment] 2019-12-24 17:24
If you don't intend to charge the user, you can use `[STPPaymentOptionsViewController](https://stripe.dev/stripe-ios/docs/Classes/STPPaymentOptionsViewController.html)` directly. It might look something like this:

```
           let viewController = STPPaymentOptionsViewController(configuration: config,
                                                                 theme: .default(),
                                                                 customerContext: customerContext,
                                                                 delegate: self)
            let navigationController = UINavigationController(rootViewController: viewController)
            delegate?.stripeController.present(navigationController, animated: true, completion: nil)
```

And then you could implement the `[STPPaymentOptionsViewControllerDelegate](https://stripe.dev/stripe-ios/docs/Protocols/STPPaymentOptionsViewControllerDelegate.html)` methods, like `paymentOptionsViewController:didSelectPaymentOption:` and `paymentOptionsViewControllerDidFinish:`, which should give you what you're looking for.

That said, your use case for `STPPaymentContext` sounds like something we should support better. I'll keep this open while we look into a way to enable this without using `STPPaymentOptionsViewController` directly.

**Comment by gowtham1094** [comment] 2019-12-25 07:17
Thanks, through STPPaymentOptionsViewController i am able to achieve my requirement.

**Comment by gowtham1094** [comment] 2020-01-20 18:22
@davidme-stripe ,  i am facing an issue in this method. If already a card is selected in that time  as soon as STPPaymentOptionsViewController presented, 

```
func paymentOptionsViewController(_ paymentOptionsViewController : STPPaymentOptionsViewController,
                                      didSelect paymentOption : STPPaymentOption) 
```

method is getting triggered automatically, so because of this there is a confusion whether it is triggering automatically or when select any one of the card.

**Comment by davidme-stripe** [comment] 2020-01-21 21:21
Hey @gowtham1094, this is expected behavior — if the new paymentOption is the same as the old one, you can ignore the message. Are you trying to take action or dismiss the sheet based on when the user is done selecting a PaymentOption? In that case, you may want to subscribe to `paymentOptionsViewControllerDidFinish:` instead.

**Comment by javobal** [comment] 2020-02-22 19:48
Hi @davidme-stripe, we also have a use case where we don't want to immediately charge the user. When i tried to use STPPaymentOptionsViewController  i noticed that the "Add new card" button no longer works, i guess because STPPaymentContext implements all of that, right ? or should it be working normally ?

**Comment by davidme-stripe** [comment] 2020-02-24 21:04
The "Add new card" button _should_ work in STPPaymentOptionsViewController without any additional configuration or glue code. What happens when you tap it? 

One thought: Are you sure you're retaining the STPPaymentOptionsViewController somewhere after presenting it? It might be falling out of scope.

**Comment by davidme-stripe** [comment] 2021-05-07 02:35
I'm closing this out, but let me know if you're still experiencing this issue. I'd also recommend trying our new [Payments UI beta](https://stripe.com/docs/mobile/payments-ui-beta) in SDK version 21.5.0.

**Closed by davidme-stripe** 2021-05-07 02:35 UTC
Labels: triaged
