### ISSUE TITLE
STPCardValidator.swift:384 error: type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by david201601** [stripe/stripe-ios#1724] opened 2020-11-28 14:59 UTC
## Summary
/ios/Pods/Stripe/Stripe/STPCardValidator.swift:384:32: error: type of expression is ambiguous without more context
        var brands = binRanges.map(\.brand)

## Code to reproduce
Indirectly build with flutter framework

## iOS version
iOS 11

## Installation method
Indirectly build with flutter framework

## SDK version
Stripe (21.0.1)

**Comment by davidme-stripe** [comment] 2020-11-30 19:52
Hi @david201601! If you run `xcode-select -p`, does it point to a copy of Xcode 11? We currently target Xcode 12.2 or later, though we support deploying to iOS 11 or later.

**Comment by AnmolRattan007** [comment] 2020-12-23 09:04
Hello @davidme-stripe! I have same issue. **xcode-select -p** this command points to /Library/Developer/CommandLineTools.

**Comment by davidme-stripe** [comment] 2021-01-04 23:49
Hi @AnmolRattan007, which version of Xcode do you have installed? I'm unable to reproduce this with Xcode 12.3 when building a Flutter app.

**Comment by AnmolRattan007** [comment] 2021-01-05 12:45
I'm using Xcode 11.3.

**Comment by AnmolRattan007** [comment] 2021-01-05 12:45
@davidme-stripe I'm using Xcode 11.3

**Comment by davidme-stripe** [comment] 2021-01-05 18:46
We only support Xcode 12 or later — is it possible to upgrade? The App Store will only support apps built with Xcode 12 starting in April.

**Comment by AnmolRattan007** [comment] 2021-01-06 13:49
Ok, I will update to Xcode 12

**Comment by davidme-stripe** [comment] 2021-01-06 23:14
This may have been fixed in version [21.2.0](https://github.com/stripe/stripe-ios/releases/tag/21.2.0). Updating to Xcode 12 is still our recommended fix.

**Closed by davidme-stripe** 2021-01-06 23:14 UTC
Labels: triaged
