### ISSUE TITLE
Keyboard issues when adding card

### ISSUE THREAD

**Issue by odedharth** [stripe/stripe-ios#1015] opened 2018-08-14 22:19 UTC
## Summary
I've upgraded Stripe from version 11.5.0 to 13.2.0, saw a problem appear on the "Add a card" screen. 

When writing the card digits it opens the iPhone digit keyboard, but when getting to the expiration date and CVC and change is to the regular digit keyboard.
This requires the user to switch keyboard again and adds friction to the process which can hurt conversion. 

## Installation method
cocoa pods 
## SDK version
13.2.0

**Comment by csabol-stripe** [comment] 2018-08-15 18:53
Hi @odedharth, thanks for the bug report. Would you mind confirming which iOS version you are hitting this on? I just tried reproducing on 11.4 but am seeing the same keyboard for card number, expiration date, and cvc input. Thanks!

**Comment by odedharth** [comment] 2018-08-15 19:38
@csabol-stripe iOS 12

**Comment by csabol-stripe** [comment] 2018-08-15 21:05
Thanks, we'll try reproducing on a device running iOS 12

**Comment by odedharth** [comment] 2018-08-15 22:46
@csabol-stripe filmed a video showing the issue https://www.dropbox.com/s/3hghri96i74ta90/stripe%20card%20bug.MOV?dl=0

**Comment by danj-stripe** [comment] 2018-08-16 16:50
Hi @odedharth,

Thanks for the video, that helps. I don't have the exact same setup as you, but I think the problem is that you're using the Google Gboard keyboard.

Looking at the code, everything looks good to me. Those text fields are set to use `UIKeyboardTypeASCIICapableNumberPad`, which should be "Specifies a number pad that outputs only ASCII digits." https://github.com/stripe/stripe-ios/blob/7116259c7b57b195d7d7f28c1521f8e65f27e99c/Stripe/STPPaymentCardTextField.m#L1147

The *difference* between the card number entry field and the other two is that we're **also** setting https://github.com/stripe/stripe-ios/blob/7116259c7b57b195d7d7f28c1521f8e65f27e99c/Stripe/STPPaymentCardTextField.m#L151

My hypothesis is that the OS completely disallows third party keyboards for `UITextContentTypeCreditCardNumber`, but on the other fields it's looking at the set of keyboards you've got enabled on your device and picking the "best" one it can for `UIKeyboardTypeASCIICapableNumberPad`.

I had to add Gboard and delete the built-in English keyboard before I was able to reproduce what you showed in your video (albeit on an iOS 11 device, but I did build with the iOS 12 SDK).

Do you have the English keyboard disabled? If not, can you narrow down the steps to reproduce further? This might be something you'll have to file a radar for, unless there's something I'm missing.

Thanks,
Dan

**Comment by odedharth** [comment] 2018-08-16 16:54
Hi @danj-stripe,

Thanks for the detailed response. Good to know that it's only for Gboard! So it's not critical then. I'll keep track on that, if it's a Gboard issue hopefully they'll fix it before iOS 12 launch. 

Thanks

**Comment by danj-stripe** [comment] 2018-08-16 17:08
Sounds good. I'm going to close this, but let us know if you find out something more that indicates there's something more we can/should do.

**Closed by danj-stripe** 2018-08-16 17:08 UTC
