### ISSUE TITLE
Double tap to set a card as default

### ISSUE THREAD

**Issue by el-quick** [stripe/stripe-ios#1035] opened 2018-10-27 01:33 UTC
As you can see in the gif below, is needed tap twice a card to set that card as default.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/395027/47598187-ac3e1f00-d955-11e8-9af2-bf31fc8b9b04.gif)

I am presenting the controller of this way:

```
let customerContext = STPCustomerContext(keyProvider: StripeClient.shared)
let paymentMethodsViewController = STPPaymentMethodsViewController(configuration: STPPaymentConfiguration.shared(), theme: STPTheme.default(), customerContext: customerContext, delegate: self as STPPaymentMethodsViewControllerDelegate)
let navigationController = UINavigationController(rootViewController: paymentMethodsViewController)
present(navigationController, animated: true)
```

... My delegate functions look like:

```
func paymentMethodsViewController(_ paymentMethodsViewController: STPPaymentMethodsViewController, didFailToLoadWithError error: Error) {
    dismiss(animated: true)
}

func paymentMethodsViewControllerDidCancel(_ paymentMethodsViewController: STPPaymentMethodsViewController) {
    dismiss(animated: true)
}

func paymentMethodsViewControllerDidFinish(_ paymentMethodsViewController: STPPaymentMethodsViewController) {
    dismiss(animated: true)
}

func paymentMethodsViewController(_ paymentMethodsViewController: STPPaymentMethodsViewController, didSelect paymentMethod: STPPaymentMethod) {
}
```

It should work with a single tap.

**Comment by karlr-stripe** [comment] 2018-11-06 11:19
Hi there,
I tried to replicate the behaviour you are seeing, but the only way I was able to do so was actually by removing the call to dismiss in the `paymentMethodsViewControllerDidFinish` delegate function. Is it possible that in your code this is also the case? I do not see any other way to reproduce the issue with the code you provided, so is that definitely the delegate code being used in your app?

To be clear, the `STPPaymentMethodsViewController` is not intended to be displayed persistently as in your image — instead, when a user has selected a payment method, the `didFinish` delegate is called and you _should_ [dismiss the view](https://stripe.github.io/stripe-ios/docs/Protocols/STPPaymentMethodsViewControllerDelegate.html#/c:objc(pl)STPPaymentMethodsViewControllerDelegate(im)paymentMethodsViewControllerDidFinish:). The `STPPaymentMethodsViewController` is designed for a 'modal' type flow, where the user taps a button in your app to select or add a payment method, the view controller pops up to handle this, and then is dismissed as soon as this is complete.

As for the issue with the `STPPaymentMethodTuple` being returned, I believe this is down to caching that is done by the `STPCustomerSession` of the currently loaded customer object — although the API request is made and the customer object's default source is updated, the `STPCustomerSession` is using a cached copy that isn't updated. However, if the `STPPaymentMethodsViewController` is used in the intended mode, where it is dismissed after a method is selected and then later displayed again when the user chooses to update their payment methods, this issues does not manifest.

I'm going to close this issue as I don't believe it is a bug with the stripe-ios library, but if you have any further questions our support team at https://support.stripe.com/email would be glad to help you with integrating the SDK in your app.

**Closed by karlr-stripe** 2018-11-06 11:19 UTC
