### ISSUE TITLE
Unable to see alert title & message when a CVC error occurs

### ISSUE THREAD

**Issue by barfoon** [stripe/stripe-ios#1026] opened 2018-10-05 22:11 UTC
## Summary
Unable to see title & message when a CVC error occurs after attempting to add a card, only `OK` action button is displayed.

## Code to reproduce
- Add a new card with number `4000 0000 0000 0101`

## iOS version
11.2

## Installation method
Cocoapods

## SDK version
Tried with `11.2`, `11.5`, `12.0`, `13.2.0`

## Other information
![image](https://user-images.githubusercontent.com/1120510/46562416-f50c3600-c8c9-11e8-8ead-a5c64b4f89f9.png)

![image](https://user-images.githubusercontent.com/1120510/46562422-fccbda80-c8c9-11e8-802f-0c4ae95c3e84.png)

![image](https://user-images.githubusercontent.com/1120510/46562430-035a5200-c8ca-11e8-844b-42bba92687ed.png)

**Comment by danj-stripe** [comment] 2018-10-16 19:32
Hi @barfoon,

Sorry about the delay in replying.

Unfortunately, I'm not able to reproduce your issue. The alert displays correctly in our sample project, and the snapshot from Xcode you provided shows that the `UIAlertController` *does* have the correct `title` (so I think it eliminates any potential problems related to the `error.localizedDescription`).

The `presentViewController:animated:completion:` method call is just using the plain UIKit implementation from `UIViewController`, we aren't doing anything unusual here.

It does look like there's something about your project, or one of your dependencies, that changes the way alerts are created or presented. The screenshot of the debugger that you've provided shows the class of `alertController` is `__ABT_UIAlertController`. I would have expected that to just be `UIAlertController`.

I suspect you have code that's swizzled the alert controller creation method that we're trying to use, and I don't think there's anything the Stripe SDK can/should do to fix this.

I'm going to close this, but if I've made a mistake please let me know and hopefully you can add more details to this issue.

Thanks,
Dan

**Closed by danj-stripe** 2018-10-16 19:32 UTC
