### ISSUE TITLE
Migrate Assets to Asset Catalog 

### ISSUE THREAD

**Issue by aasatt** [stripe/stripe-ios#382] opened 2016-07-28 01:07 UTC
To make it easier to diagnose your issue, please fill out the following:

## Summary

I could not get the accent color of the STPTheme to tint the images. Migrating the assets to an asset catalog fixed the issue. 

## Code to reproduce

Present the payment method view

## iOS version

10

## Installation method

Cocoapods

## SDK version

Current 

## Other information

I have already forked it and made the changes. I don't know your plans for the sdk and the reason for not having a catalog so I didn't create a pull on it yet.

**Comment by jflinter** [comment] 2016-07-29 01:01
Interesting. Just to confirm @aasatt - are you only seeing this on iOS 10?

**Comment by aasatt** [comment] 2016-07-29 01:06
I'm actually seeing it on [iOS 9 (9.2.1)](https://i.sli.mg/QQvirh.png) as well.

**Comment by jflinter** [comment] 2016-08-13 00:58
@aasatt - we're having trouble reproducing this on our end. Can you send us a couple of things:
- The contents of your `Podfile.lock`
- If possible, a small project that reproduces this issue? You can just .zip it up and email it to jack.flintermann@stripe.com .
Thanks!

**Comment by bdorfman** [comment] 2016-08-29 19:49
We still can't reproduce this bug, so I'm going to close it for now. If anyone else also has this problem or can send us more information on how to reproduce, please reopen the issue.

**Closed by bdorfman** 2016-08-29 19:49 UTC
