### ISSUE TITLE
iOS STPPaymentHandler ConfirmSetupIntent, "Received unknown parameter client_secret"

### ISSUE THREAD

**Issue by imimoises** [stripe/stripe-ios#1336] opened 2019-08-30 00:26 UTC
## Summary
Im testing my integration of Saving a card using stripe's SetupIntents, and I have followed all the steps location in the documentation, yet when I am try to confirm the setup intent,  "Received unknown parameter client_secret" is what I am getting.

## Code to reproduce
`let setupIntentParams = STPSetupIntentConfirmParams(clientSecret: clientSecret)
        setupIntentParams.paymentMethodID = paymentMethod.stripeId
        let paymentManager = STPPaymentHandler.shared()
 
        guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else {
            return
        }
  
        paymentManager.confirmSetupIntent(setupIntentParams, with: appDelegate, completion: { [weak self] (status, setupIntent, error) in
            guard error == nil else {
                completion(WCError(error), false)
                return
            }
            switch (status) {
            case .succeeded:
                // Step 4: if succeed, we let it know to the backend
                self?.commitSetupIntent(setupIntent: setupIntent, completion: completion)
            case .canceled:
                completion(nil, true)
            default:
                completion(WCError(), false)
            }
        })`

**Comment by yuki-stripe** [comment] 2019-08-30 00:51
Closing as dupe of #1337

**Closed by yuki-stripe** 2019-08-30 00:51 UTC
