### ISSUE TITLE
Subscription with iOS and PHP

### ISSUE THREAD

**Issue by SimonFernandes7** [stripe/stripe-ios#1596] opened 2020-06-23 16:33 UTC
## Summary

In my current iOS project, I need the user to subscribe to a feature. The back-end is in PHP, I have used pod to install Stripe SDK.

The backend API needs a **STPToken** to make the user subscribe to a feature, and by using **STPPaymentContext** I'm not able to get this token. Even the following function is deprecated, 

`func addCardViewController(_ addCardViewController: STPAddCardViewController, didCreateToken token: STPToken, completion: @escaping STPErrorBlock)`

May I know where am I going wrong, is there any other way for handling subscription? Need to even provide cancel and update subscription feature. 
## Code to reproduce

Have referred to the example provided here -> https://github.com/stripe/stripe-ios/tree/master/Example

## iOS version
Deployment Target: 11.0 to Latest 13.5

## Installation method
Pod 

## SDK version
(19.2.0)

## Other information
Let me know if any changes are required in the backend. Also, How can I fetch subscriptions prices according to the region or its currencies.

**Comment by aliriaz-stripe** [comment] 2020-06-23 17:05
@SimonFernandes7 hello!

Those are good questions, I'll answer here but also going to close this issue as its not a bug/feature request for the SDK. 
I would like to chat more to fully unblock you so if you have more questions, you can write in to Support at https://support.stripe.com/contact or hop by the freenode #stripe channel where developers can help you with your technical questions: https://webchat.freenode.net/

> I'm not able to get this token
Tokens are a legacy integration, they are replaced with PaymentMethods which all the prebuilt components of the iOS SDK create by default now. Just like Tokens, PaymentMethods can be attached to Customer objects on Stripe and used to create Subscription
To collect a PaymentMethod, you do steps 2 and 3 from here: https://stripe.com/docs/payments/accept-a-payment-synchronously#ios-create-checkout-screen

> May I know where am I going wrong, is there any other way for handling subscription?
This doc (https://stripe.com/docs/billing/subscriptions/fixed-price) helps in covering how Subscription creation works on Stripe. This doc is mostly geared toward Stripe Elements but you'd substitute those parts with the iOS SDK, to create a PaymentMethod token, combine it with the doc I mentioned above.

> Need to even provide cancel and update subscription feature.
Subscription updates are a server-side function, so you do them on your backend and provide endpoints for your iOS app to call.

> How can I fetch subscriptions prices according to the region or its currencies.
Prices can be fetched according to currency: https://stripe.com/docs/api/prices/list
Listing by region isn't a concept on Stripe so you have to handle that on your end, through `metadata` on the Price object and filtering on that.

Hope the above helps! If you have more questions, please do write in to Support or drop by https://webchat.freenode.net/ and we can help you there with technical/API related questions!

**Closed by aliriaz-stripe** 2020-06-23 17:05 UTC

**Comment by SimonFernandes7** [comment] 2020-06-23 17:51
Thanks for your help @aliriaz-stripe.

One more question, can the customer change his payment method later-on(change card), and will it affect the current subscription of the customer.

**Comment by aliriaz-stripe** [comment] 2020-06-23 18:23
@SimonFernandes7  sure, answers below: 

> can the customer change his payment method later-on(change card)

Yes, your integration maintains the Customer object on Stripe can choose to update the payment methods attached to the Customer

> will it affect the current subscription of the customer.

Your integration has to update the `default_payment_method` field on the Subscription object to have the Subscription charge the newly attached PaymentMethod (instead of the older one)
