### ISSUE TITLE
SFSafariViewController unable to view the proper Html

### ISSUE THREAD

**Issue by shantaramk** [stripe/stripe-ios#1381] opened 2019-09-18 05:44 UTC
I have been using the stripe SDK to execute the payment but as user perspective, we are unable to view the complete authorization and fail authorization button at the proper location.
as of now, we have to scroll the web view horizontally.

Here is code that i have written

  ```
      let paymentIntentParams = STPPaymentIntentParams(clientSecret: clientSecret)
        paymentIntentParams.paymentMethodId = paymentMethodId
        
        let paymentManager = STPPaymentHandler.shared()
        
        paymentManager.confirmPayment(withParams: paymentIntentParams, authenticationContext: self) { (status, paymentIntent, error) in
            print(error ?? "")
            print(paymentIntent ?? "")
            switch (status) {
            case .failed:
                dismissLoader()
                if error != nil {
                    showAlert(message: error?.localizedDescription ?? "", inViewController: self)
                }
            case .canceled:
                dismissLoader()
                if error != nil {
                    showAlert(message: error?.localizedDescription ?? "", inViewController: self)
                }
            case .succeeded:
                self.showPaymentSuccessAlert()
            }
        }
    
```

## iOS version
**I have been using the iphone 6s version 10.2.1**

## Installation method
I installed the stripe using pod

## SDK version
STPSDKVersion = "17.0.0";
![IMG_0933](https://user-images.githubusercontent.com/7990309/65115676-b05bab00-da05-11e9-8f27-d8ce119df0b5.png)

**Comment by shantaramk** [comment] 2019-09-18 05:45
![IMG_0933](https://user-images.githubusercontent.com/7990309/65115618-a174f880-da05-11e9-9536-d4d9666b4e59.png)

**Comment by csabol-stripe** [comment] 2019-09-19 18:24
hi @shantaramk, I was able to reproduce what you're seeing using a 10.2 simulator and have reached out to our web team to have them investigate. FWIW I was not seeing this behavior on iOS 10.3+ if that helps. Also these are just Stripe test pages so won't be what your customers see :) I'll update this issue when I hear back from our web team about the fix

**Comment by shantaramk** [comment] 2019-09-20 08:14
Hi @csabol-stripe, Yes I understand our customer will not get interact with this screen ever because we are using the sandbox mode.
thanks for update

**Comment by csabol-stripe** [comment] 2019-09-23 21:25
Due to low usage numbers for pre-iOS 11 and because this won't affect cardholders, our web team isn't considering this a priority fix. Closing the issue for now, feel free to reach out directly if you have more context to share @shantaramk !

**Closed by csabol-stripe** 2019-09-23 21:25 UTC
Labels: triaged
