### ISSUE TITLE
STPPaymentHandler does not localize Error response

### ISSUE THREAD

**Issue by letrongtriet** [stripe/stripe-ios#1401] opened 2019-10-02 08:09 UTC
## Summary
STPPaymentHandler does not localize Error response when confirming a payment intent (Finnish language) even thought there is localization for Finnish.

## Code to reproduce
- Use card `4000 0000 0000 3063`
- Choose `Fail authentication`
- Error response is not localized

`Error Domain=STPPaymentHandlerErrorDomain Code=5 "We are unable to authenticate your payment method. Please choose a different payment method and try again." UserInfo={NSLocalizedDescription=We are unable to authenticate your payment method. Please choose a different payment method and try again.}`

## iOS version
13.0.2

## Installation method
Cocoapods

## SDK version
17.0.2

**Comment by yuki-stripe** [comment] 2019-10-02 14:19
Hi @letrongtriet 

Thank you for reporting!  This should be fixed in the next release.

**Comment by davidme-stripe** [comment] 2019-10-04 23:04
This is fixed in 18.0.0. (And is a dupe of #1325.)

**Closed by davidme-stripe** 2019-10-04 23:04 UTC
Labels: fixed in master, kind:bug, triaged
