### ISSUE TITLE
Stripe Pod and xcode 13

### ISSUE THREAD

**Issue by darking09** [stripe/stripe-ios#1893] opened 2021-10-26 19:24 UTC
Hi, I'm trying to run an app with your stripe-ios with cocoapods and xcode 13, but after the add this in my own podfile always I have the next error:

`
error: using bridging headers with module interfaces is unsupported
Command CompileSwiftSources failed with a nonzero exit code
`
I'm using the following stripe-ios version:

- Stripe (21.9.0):
    - Stripe/Stripe3DS2 (= 21.9.0)
    - StripeCore (= 21.9.0)
    - StripeUICore (= 21.9.0)
  - Stripe/Stripe3DS2 (21.9.0):
    - StripeCore (= 21.9.0)
    - StripeUICore (= 21.9.0)
  - StripeCore (21.9.0)
  - StripeUICore (21.9.0):
    - StripeCore (= 21.9.0)
    
Can somebody help me with that?

Thanks

**Comment by davidme-stripe** [comment] 2022-08-04 18:28
Closing this issue, as we're not able to reproduce it. Let us know if you're still experiencing this!

**Closed by davidme-stripe** 2022-08-04 18:28 UTC
Labels: triaged
