### ISSUE TITLE
[BUG] Xcode 14 beta 1 - build error "Stored properties cannot be marked potentially unavailable with '@available'"

### ISSUE THREAD

**Issue by jtouzy** [stripe/stripe-ios#1976] opened 2022-06-07 23:23 UTC
## Summary
Xcode 14 beta 1 shows a build error in `CardDetailsEditView`, only on macOS Ventura Beta.
Same project opened on macOS Monterrey 12.4 does not have any problem.
I just don't really understand why that @availability shouldn't be applied to stored vars from now...

<img width="1136" alt="Screenshot 2022-06-07 at 16 21 07" src="https://user-images.githubusercontent.com/5709133/172499142-4cd485f1-c3c1-4919-afd2-90950d54a0e2.png">

Multiple derived data cleanings, nothing better.

## Code to reproduce
--

## iOS version
iOS 16.0

## Installation method
SPM.

## SDK version
Stripe 21.9.0

**Comment by davidme-stripe** [comment] 2022-06-07 23:25
Dupe of https://github.com/stripe/stripe-ios/issues/1973. A workaround branch is available in that issue.

**Closed by davidme-stripe** 2022-06-07 23:25 UTC
Labels: kind:bug

**Comment by jtouzy** [comment] 2022-06-07 23:29
Sorry, the related issue title was not that explicit. Thanks for changing it.
