### ISSUE TITLE
Picker Views Don't Update on First Selection

### ISSUE THREAD

**Issue by hyerra** [stripe/stripe-ios#533] opened 2017-01-08 02:55 UTC
To make it easier to diagnose your issue, please fill out the following:

## Summary
Prefilled information now works; however, the picker view doesn't update to the correct country on the first selection. United States is automatically selected but I have to swipe up and back down to actually select the United States (check the attached video for this to be more clear -- Country Bug.zip in Other Information).

## Code to reproduce
Any project using Stripe's STPShippingAddressViewController has this issue. Just present the View Controller and try changing the country.

## iOS version
iOS 10.2

## Installation method
Cocoapods

## SDK version
9.3.0

## Other information
A video showing the issue clearly is attached.
[Country Bug.zip](https://github.com/stripe/stripe-ios/files/691848/Country.Bug.zip)

**Comment by bdorfman-stripe** [comment] 2017-01-10 00:58
Hi @hyerra,

Can you give me a further code sample to work with or more specific repro steps? If you try out the example app included with the sdk, it seems to show the shipping screen with the country pre-filled correctly, so I am not 100% sure how to reproduce this issue.

Thanks!

**Comment by hyerra** [comment] 2017-01-14 01:38
Hi @bdorfman-stripe ,
Yes! I will be able to provide an example project shortly. Sorry for the delay, it's just tough to find time sometimes as high school can be a bit busy at times haha.

Harish

**Comment by bdorfman-stripe** [comment] 2017-01-24 20:13
Closing for now as I can't reproduce on 9.3.0. It is possible you were actually on master or another branch and not the latest release? Feel free to open a new issue if you continue to have this problem on the latest release.

**Closed by bdorfman-stripe** 2017-01-24 20:13 UTC
