### ISSUE TITLE
[BUG]  Apple Pay duplicate payment methods

### ISSUE THREAD

**Issue by Kurayammi** [stripe/stripe-ios#2679] opened 2023-06-21 10:24 UTC
After use Apple Pay duplicate payment methods on payments sheet.
Version of sdk is 23.9.1
How can I prevent it?

<img width="442" alt="Снимок экрана 2023-06-21 в 1 24 09 PM" src="https://github.com/stripe/stripe-ios/assets/67389689/cc29e832-52ff-42e7-9655-b83f27f5e09a">

**Comment by seanzhang-stripe** [comment] 2023-06-21 11:22
Hi @Kurayammi Can you share more details here? If you can share the detailed steps to produce, it'll be very helpful.

**Comment by Kurayammi** [comment] 2023-06-21 12:08
@seanzhang-stripe Hi)
I just use Apple Pay several times in a row. And after every use, payment method add to payment sheet

**Comment by seanzhang-stripe** [comment] 2023-06-21 12:23
Can you share the code? For example, how you create the PaymentSheet Configuration, what param you pass in to create the PaymentIntent, as well as the relevant PaymentIntent IDs?

**Comment by Kurayammi** [comment] 2023-06-21 12:32
Sure
<img width="1198" alt="Снимок экрана 2023-06-21 в 3 30 12 PM" src="https://github.com/stripe/stripe-ios/assets/67389689/69426af6-de32-4407-b61e-8cb2c120da2d">
<img width="1379" alt="Снимок экрана 2023-06-21 в 3 31 53 PM" src="https://github.com/stripe/stripe-ios/assets/67389689/380dd29e-9fc8-4624-8d19-424f0f26e22b">

**Comment by yuki-stripe** [comment] 2023-06-21 23:04
Thanks for raising this @Kurayammi.  This is expected behavior today - since you're using a SetupIntent, the Apple Pay card is saved to your Customer object each time you check out. You'd see the same behavior if you entered card details manually.

We're considering changing the behavior to _hide_ saved cards if they came from Apple Pay - is that behavior you want?

**Comment by Kurayammi** [comment] 2023-06-22 08:06
@yuki-stripe I need to save card from Apple Pay if it has not been saved before. If it already saved - do not add it to payments sheet

**Comment by yuki-stripe** [comment] 2023-06-22 16:29
@Kurayammi Thanks for your reply - that makes sense. We would wouldn't **show** saved Apple Pay cards in this screen
![image](https://github.com/stripe/stripe-ios/assets/47796191/1638ad97-1b09-4492-bea2-6c9ddeeb2ac5)
 However, they would still be saved on the Stripe Customer object and still available for you to charge on your backend. Does that work for you?

Alternatively, there's work planned to deduplicate cards - I think this is more in line with what you're asking for. I don't have an ETA for either of these features but your feedback is greatly appreciated!

**Comment by Kurayammi** [comment] 2023-06-23 08:44
@yuki-stripe yes, that would be nice. Thanks!

**Comment by ViljamHaanpaa** [comment] 2023-12-19 22:56
hey, has this "deduplicate cards" fix already somewhere?

**Comment by seanzhang-stripe** [comment] 2023-12-21 01:36
@ViljamHaanpaa You can update to SDK version [23.18.1](https://github.com/stripe/stripe-ios/blob/master/CHANGELOG.md#23181-2023-10-30) or above, where PaymentSheet no longer displays saved cards that originated from Apple Pay.

**Comment by ViljamHaanpaa** [comment] 2023-12-21 15:18
Hey, im using "@stripe/stripe-react-native" and I import the paymentsheet from there using 
const { initPaymentSheet, presentPaymentSheet } = useStripe().

do i need to use the separate paymentsheet api to get it working?

**Comment by ViljamHaanpaa** [comment] 2023-12-21 21:20
@seanzhang-stripe  so just to clarify I use react-native version of the stripe no the ios. And from there initPaymentSheet and applePay{} in there.

**Comment by seanzhang-stripe** [comment] 2023-12-22 04:55
Hi @ViljamHaanpaa Based on the [podspec](https://github.com/stripe/stripe-react-native/blob/v0.35.0/stripe-react-native.podspec#L5), stripe-react-native 0.35.0 is already using Stripe iOS SDK 23.18.0 and above. So this change is already included in the stripe-react-native SDK that your project is using.

To make sure you project is getting the latest version of Stripe iOS SDK. I'd suggest you to delete `Podfile.lock` file and `Pods` directories, and run `pod install` command to install the dependencies.

**Comment by sfriedman-stripe** [comment] 2023-12-24 06:57
Closing, as the issue has been resolved

**Closed by sfriedman-stripe** 2023-12-24 06:57 UTC
Labels: kind:bug, triaged
