### ISSUE TITLE
STPCheckoutOptions.h import issue with CocoaPods & Frameworks

### ISSUE THREAD

**Issue by keith** [stripe/stripe-ios#171] opened 2015-06-11 21:20 UTC
We're including Stripe via CocoaPods in our project. Using frameworks for iOS 8 we see a build error with version 4.0.3.

![screen shot 2015-06-11 at 14 19 43](https://cloud.githubusercontent.com/assets/283886/8118617/ef64cdb6-1044-11e5-8f27-553ade67e580.png)

![screen shot 2015-06-11 at 14 19 34](https://cloud.githubusercontent.com/assets/283886/8118618/ef65272a-1044-11e5-84b7-7f302d811605.png)

Here's an abridged version of our `Podfile`

```ruby
platform :ios, "8.0"
use_frameworks!

...
    pod 'Stripe'
    pod 'Stripe/ApplePay'
...
```

This is not an issue with version 3.1.0

**Comment by jflinter** [comment] 2015-06-15 16:41
Hmm, frustrating! Sorry you're seeing this; I've worked pretty hard to make sure our SDK plays nicely with Cocoapods frameworks.

That being said, I'm unable to reproduce this issue in a brand new app with that exact `Podfile`. Some more debugging questions that would be helpful to know:
- If you start a new Xcode project with that `Podfile` and try and build it, do you still see the error?
- Which versions of Xcode and Cocoapods are you using?
- Is this a Swift or Objc project?

Happy to try and help debug this further.

**Comment by keith** [comment] 2015-06-15 17:02
I think part of the issue here might be that we have a framework that also depends on this SDK. It looks like this:

- Main App depends on stripe
- Main App depends on framework
- framework depends on stripe

**Comment by jflinter** [comment] 2015-06-16 19:27
Hmm, I've tried to replicate your setup but everything's building fine. Think you could put together a small sample project that recreates this error on github so I can use it to debug things?

**Comment by jflinter** [comment] 2015-06-16 19:28
(@keith: you're also welcome to message me directly if it'd be easier; I'm jack@stripe.com)

**Comment by keith** [comment] 2015-06-16 19:40
I'll try and create an example project soon. Thanks!

**Comment by keith** [comment] 2015-06-17 16:48
Possible related https://github.com/CocoaPods/CocoaPods/issues/3666 and https://github.com/CocoaPods/CocoaPods/issues/3654

**Comment by TotemTraining** [comment] 2015-06-27 14:00
Same problem here.  Project builds and runs fine, but I can no longer debug any of my code anywhere in the entire project.

![screen shot 2015-06-27 at 9 59 13 am](https://cloud.githubusercontent.com/assets/9408906/8392274/491259bc-1cb3-11e5-8034-14217429a240.png)

**Comment by jflinter** [comment] 2015-06-28 20:49
That's really annoying; I'm sorry for the trouble you're seeing.
While we're looking into this, as a workaround I'd suggest only building the core subspecs of our SDK - in other words, changing your `Podfile` from
```ruby
pod 'Stripe'
pod 'Stripe/ApplePay' # optional
```
to
```ruby
pod 'Stripe/Core'
pod 'Stripe/ApplePay' # optional
```
Let me know if that's helpful.

**Comment by keith** [comment] 2015-07-03 01:29
Interestingly, after trying this again, I no longer see this error. I am seeing a different warning here though.

<img width="327" alt="screen shot 2015-07-02 at 18 28 25" src="https://cloud.githubusercontent.com/assets/283886/8491028/25cbdbde-20e8-11e5-9f16-98bbb3c5d1cb.png">

Not sure why it's expecting this since this file isn't included.

**Comment by keith** [comment] 2015-07-03 01:30
I've also upgraded to Xcode 6.4 since last time, not sure how much that affects this case.

**Comment by keith** [comment] 2015-07-03 01:31
Related: https://github.com/realm/realm-cocoa/issues/2090 & https://github.com/CocoaPods/CocoaPods/pull/3550

**Comment by keith** [comment] 2015-07-03 01:40
Looks like this was fixed with CocoaPods `0.38.0.beta.1`

**Comment by TotemTraining** [comment] 2015-07-04 02:55
Yup verified 0.38.0.beta.1 cleared up debugging issues.

**Comment by jflinter** [comment] 2015-07-08 20:16
Great, thanks for clearing this up @keith @TotemTraining. I'm going to close this issue then, but feel free to re-open if anything else crops up around this.

**Comment by jflinter** [comment] 2015-07-08 22:49
Actually @keith @TotemTraining, I think I just fixed this anyway: #180

**Comment by keith** [comment] 2015-07-08 22:50
Awesome thanks!

**Comment by keith** [comment] 2015-07-08 23:18
@jflinter is there going to be a release with this fix?

**Comment by jflinter** [comment] 2015-07-08 23:34
Yep, working on it now.

**Comment by TotemTraining** [comment] 2015-07-15 15:33
This is no longer working for me.  I initially updated to cocoapods beta and it fixed it, but all of the sudden I am getting the same Stripe errors when trying to debug anything in lldb again.

**Comment by keith** [comment] 2015-07-27 18:15
There's an issue open on CocoaPods about this non-modular stuff https://github.com/CocoaPods/CocoaPods/issues/3847

**Comment by keith** [comment] 2015-07-31 18:37
Seems like this is definitely still an issue with the newest version of CocoaPods and Stripe.

**Comment by jflinter** [comment] 2015-08-03 23:18
Yeah, I've actually now been able to reproduce it locally. It looks like
the `has_include` guards in `Stripe.h` are at fault here. Working on this
now.

**Comment by keith** [comment] 2015-08-03 23:20
Awesome, glad you could get to the bottom of it!

**Comment by keith** [comment] 2015-08-05 16:50
Just realized that the 0.38.0 launch [blog post](http://blog.cocoapods.org/CocoaPods-0.38/) mentions this explicitly. Under the "Removal of the Enviroment Header" section.

**Comment by jflinter** [comment] 2015-08-05 23:37
Ok, I've fixed this with a somewhat-heavily-handed approach by removing our subspecs, along with the `__has_include` checks, in #187. Ultimately, maintaining those was proving to be more trouble than it was worth. I'm going to cut a new release tomorrow that I'd love for you to test, @keith. Thanks for all your patience here!

**Closed** 2015-08-05 23:37 UTC

**Comment by keith** [comment] 2015-08-05 23:39
Awesome, I'll update as soon as I see the new release!
