### ISSUE TITLE
[BUG] Incorrect functionality vs Android SDK

### ISSUE THREAD

**Issue by chrisjenx** [stripe/stripe-ios#3443] opened 2024-03-21 02:08 UTC
## Summary
Confirming a Mandate works differently to Android SDK.

Issue 1:
Why do we need the customer ephemeral key at this point? For bank mandates it's not even required for the PaymentLauncher on Android.
Issue 2
The main issue is that your version of STPCustomerContext requires the raw json vs the actual key on android:
```
 PaymentSheet.CustomerConfiguration(
//                id = stripeSetupIntent.customerId,
//                ephemeralKeySecret = eKey,
//            )
```

Can we omit the whole STPPaymentContext or at least only pass through just the Key so I don't have to completely change a bankend call when creating a setup intent.

```
let setupIntentParams = STPSetupIntentConfirmParams(
            clientSecret: stripeSetupIntentResponse.clientSecret,
            paymentMethodType: .USBankAccount
        )
    
        let paymentContext = STPPaymentContext(
            customerContext: STPCustomerContext(
                keyProvider: MyCustomerEphemeralKeyProvider(
                    customerKey: stripeSetupIntentResponse.ephemeralKey!
                )
            )
        )
        return await withCheckedContinuation { continuation in
            STPPaymentHandler.shared().confirmSetupIntent(
                setupIntentParams, with: paymentContext
            ) { (status, intent, error) in
                if(error != nil) {
                    return continuation.resume(returning: AddPaymentMethodResult.Failed(
                        error: KotlinThrowable(message: error?.localizedDescription))
                    )
                }
                switch status {
                case .failed:
                    continuation.resume(returning: AddPaymentMethodResult.Failed(error: KotlinError()))
                case .canceled:
                    continuation.resume(returning: AddPaymentMethodResult.Canceled())
                case .succeeded:
                    continuation.resume(returning: AddPaymentMethodResult.Completed())
                @unknown default:
                    fatalError()
                }
            }
        }
```

## iOS version
15+

## Installation method
Pods

## SDK version
22.36

## Other information

Thirdly why are your SDK so far apart and inconsistant, iOS and Android basically work the same these days, it's not great they work completely differently.

**Comment by porter-stripe** [comment] 2024-04-15 14:21
Closing as a dupe of https://github.com/stripe/stripe-ios/issues/3442

**Closed by porter-stripe** 2024-04-15 14:21 UTC
Labels: kind:bug
