### ISSUE TITLE
[Feature] STPCardFormView should allow for customization similar to STPPaymentCardTextField.

### ISSUE THREAD

**Issue by ryanluce** [stripe/stripe-ios#1971] opened 2022-06-01 15:57 UTC
## Is your feature request related to a problem? Please describe.
STPCardFormView should allow for the textfields within it to be customized similar to STPPaymentCardTextField. We have specific fonts for our app, much like other apps. We can implement them in  STPPaymentCardTextField but not STPCardFormView. 

## Describe the solution you'd like
STPCardFormView should implement a similar private allFields property and iterate through them with setters for font, font color etc. 

## Describe alternatives you've considered
An alternative would be to just make the textfields in STPCardFormView to be public so they're accessible and not internal when using the SDK through a dependency manager like cocoapods.

**Comment by davidme-stripe** [comment] 2022-06-01 22:03
Thanks for filing this! I think this is a duplicate of https://github.com/stripe/stripe-ios/issues/1932, we'll track this request there.

**Closed by davidme-stripe** 2022-06-01 22:03 UTC
Labels: kind:improvement
