### ISSUE TITLE
Card Number textfield of STPPaymentCardTextField shifts too far left when resigning to next text fields.

### ISSUE THREAD

**Issue by elevins** [stripe/stripe-ios#623] opened 2017-03-31 22:53 UTC
## Summary
When i display the text field in a view and fill out the card number the next text fields slide over as intended, however the card number text field (now just 4 chars) slides too far to the left and is partially behind the card image. Attached relevant photos.

## Code to reproduce

    var paymentTextField:STPPaymentCardTextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        self.edgesForExtendedLayout = []
        
        let saveButton = UIBarButtonItem(title: "Save", style: .done, target: self, action: #selector(saveButtonTapped))
        saveButton.setTitleTextAttributes([NSForegroundColorAttributeName : UIColor.gray], for: .disabled)
        saveButton.isEnabled = false
        self.navigationItem.rightBarButtonItem = saveButton
        
        paymentTextField = STPPaymentCardTextField()
        paymentTextField.delegate = self
        paymentTextField.textColor = StyleManager.textTheme()
        view.addSubview(paymentTextField)
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        let padding = CGFloat(15);
        let width = self.view.frame.width - (padding*2);
        //let bounds = self.view.bounds;
        self.paymentTextField.frame = CGRect(x: padding, y: padding, width: width, height: 44)
        
    }

## iOS version
iOS 10.2

## Installation method

Cocoapods

## SDK version

9.4.0

## Other information

<img width="365" alt="screen shot 2017-03-31 at 3 43 09 pm" src="https://cloud.githubusercontent.com/assets/1833688/24571982/cf2d355a-1629-11e7-920c-28ae95cbd4eb.png">

<img width="371" alt="screen shot 2017-03-31 at 3 43 18 pm" src="https://cloud.githubusercontent.com/assets/1833688/24571984/d378df24-1629-11e7-80f4-09e55d9a9c23.png">

**Comment by bdorfman-stripe** [comment] 2017-04-05 17:18
Thanks for the report, we'll investigate!

**Comment by jesxr44** [comment] 2017-04-18 10:40
I'm experiencing something similar. In debug mode, the form shows number + expiry date + cvc, but in Release mode, just shows number.

iOS version: 10.3
Installation method: Cocoapods
SDK Version: Stripe 9.4.0
![img_2358](https://cloud.githubusercontent.com/assets/3900622/25126891/17e1a0b6-2434-11e7-8ec6-57de39d4322e.PNG)

**Comment by jesxr44** [comment] 2017-04-18 14:01
Finally I have found that the issue was caused by another framework.

**Comment by bdorfman-stripe** [comment] 2017-04-18 17:16
@elevins We are having trouble reproducing the issue you describe. Do you have a simple example project or file you can send us?

**Comment by elevins** [comment] 2017-04-18 20:06
@jesxr44 Out of curiosity what framework was causing the issue seems to be the same for me as the same code in a fresh project causes doesn't have the same issue.

**Comment by elevins** [comment] 2017-04-18 20:12
@bdorfman-stripe Its a pretty convoluted project at this point. I can try to parse out and simplify, while keeping the error, and let you know. Thanks

**Comment by jesxr44** [comment] 2017-04-19 07:11
@elevins The framework that was causing the issues it's "WalkMe"

**Comment by bdorfman-stripe** [comment] 2017-04-20 18:31
Closing for now, as this seems to be an issue with another framework. Please open a new issue if you continue to have trouble or are able to reproduce with Stripe. Thanks!

**Closed by bdorfman-stripe** 2017-04-20 18:31 UTC
