### ISSUE TITLE
Set barTintColor on navBars for PaymentMethodsViewController and AddCardViewController

### ISSUE THREAD

**Issue by idris** [stripe/stripe-ios#527] opened 2017-01-02 20:09 UTC
When using the ["simple" integration](https://stripe.com/docs/mobile/ios/standard#theming) the barTintColor of `PaymentMethodsViewController` and `AddCardViewController` is not set, so the navBar ends up being whatever `primaryBackgroundColor` is set to.

Instead, [according to the screenshot in the docs](https://stripe.com/docs/mobile/ios/standard#theming) it should be set to `secondaryBackgroundColor`.

As an alternative, we could add an additional theme value for `navBarBackgroundColor`.

## SDK version

v9.2.0

## Other information

I'd be happy to submit a pull request for this if that helps.

**Comment by bdorfman-stripe** [comment] 2017-01-03 19:05
Hi idris,

Are you seeing this happen when pushing the `PaymentMethodsViewController` or presenting it? We should be theming the nav bar if you use the present method on `STPPaymentContext` but if you are pushing it, we do not alter the nav bar, as in that case the navigation controller/bar are owned by you and are used elsewhere in the app (whereas for presenting we create our own new navigation controller that we can alter without worrying about unintended side effects elsewhere in your app).

If you are experiencing this issue when presenting, please re-open and we will investigate further, but if it is on push it is working as intended. I can add some clarification to the docs to make this clearer if it is currently confusing.

**Comment by idris** [comment] 2017-01-03 19:06
@bdorfman-stripe I am calling `paymentContext.presentPaymentMethodsViewController()`, not pushing it.

I don't have permission to re-open the issue.

**Comment by bdorfman-stripe** [comment] 2017-01-03 19:09
Hmm, can you provide some example code? In the example app you can change the default theming and it seems to be correctly changing the nav bar color, so I am not sure how to reproduce your bug.

**Comment by idris** [comment] 2017-01-03 19:28
@bdorfman-stripe thanks for your willingness to help.  Here's our code (the relevant parts)

```swift
    let config = STPPaymentConfiguration.shared()
    // ... config initialized here
    let theme = STPTheme.default()
    theme.primaryBackgroundColor = UIColor.blue
    theme.secondaryBackgroundColor = UIColor.green
    // no matter what we set in theme, the navbar is transparent (or colored with `primaryBackgroundColor`)
    let paymentContext = STPPaymentContext(apiAdapter: ConfigurableSTPBackendAPIAdapter.sharedClient, configuration: config, theme: theme)
    var topController = UIApplication.shared.keyWindow?.rootViewController
    paymentContext.hostViewController = topController
    paymentContext.presentPaymentMethodsViewController()
```

And here's a screenshot:
<img width="376" alt="screen shot 2017-01-03 at 11 26 50 am" src="https://cloud.githubusercontent.com/assets/13989/21620095/8cf2a114-d1a7-11e6-8be3-cc88321386d5.png">

In this screenshot, with the given code, I expect the navbar to be green, not blue.  (These colors are used just to highlight the problem.  In reality we're just trying to get it working on the default theme)

**Comment by idris** [comment] 2017-01-03 19:36
Also, on the default theme this causes an issue with the status bar where you get white text on a gray background.  Screenshot:
<img width="377" alt="screen shot 2017-01-03 at 11 33 17 am" src="https://cloud.githubusercontent.com/assets/13989/21620312/8fb80a5a-d1a8-11e6-92b6-de65a11a2aef.png">

In digging through the code a bit, I don't see anywhere where the navigationBar's `barTintColor` is set.  I only see the nav items being styled: https://github.com/stripe/stripe-ios/blob/master/Stripe/STPPaymentMethodsViewController.m#L157-L163

**Comment by bdorfman-stripe** [comment] 2017-01-04 00:44
Ah, I think the screenshot in the docs is incorrect. The navigation bar is supposed to be set to your primaryBackgroundColor on your theme. I will make a note to have the screenshot in the documentation updated. 

If you want to have the navigation bar have a custom color that is not primary background color, we recently added a change to let you set the `stp_theme` on the nav bar directly, separate from the view controller. It is currently in master, and will be in our next release which should be later this week.

I'm not sure how you got the status bar color to be different? We set `preferredStatusBarStyle` to either light or dark based on your primary background color. Again, it seems to be working in our example app correctly, but perhaps based on your navigation stack setup it might not be getting passed through properly. If you give some more code examples to reproduce that issue I can try to help figure it out.

**Comment by idris** [comment] 2017-01-04 01:10
@bdorfman-stripe hmm.. if the screenshot is incorrect, and what's happening is the intended behavior, I think the default behavior should be changed.  With the current behavior, all 3 of the screenshots on this page will look _way_ uglier: https://stripe.com/docs/mobile/ios

All of those screenshots in the docs currently look good because to the navbar color being set to `secondaryBackgroundColor`.

That's just my opinion.. I suppose it's upto you & the designers to decide the right defaults.

---

At any rate, about the `stp_theme` change in `master`... could you give a snipper on how to set the `stp_theme` on the navbar?  I can't figure out how to get a reference to the navBar before (or after) calling `presentPaymentMethodsViewController`

**Comment by bdorfman-stripe** [comment] 2017-01-04 01:21
In master `stp_theme` is a settable property on UINavigationBar via a category method. You can access the nav bar the same way as you would normally do. From a reference to a view controller: `viewController.navigationController.navigationBar`

I'll have to get back to you on the color change issue. Thanks for your patience.

**Comment by idris** [comment] 2017-01-04 20:49
@bdorfman-stripe in response to https://github.com/stripe/stripe-ios/pull/528#issuecomment-270457276:
> @idris I think both of those issues are a problem with your configuration. If you run the included example app you can see the status bar changes correctly with theme color and the cancel button is present. For status bar I would make sure you are using the UIViewControllerBasedStatusBarAppearance flag in your plist and/or not globally overriding the status bar color somewhere else in your app. For Cancel, I would make sure that you are not changing left bar button item anywhere (or changing its color to white).
> 
> If you are still having trouble, lets take it back to the issue thread and not here.

I'll try and figure out my status bar issue, but the "Cancel" button is missing in the Sample app as well.  Here are steps to reproduce:
1. Modify [`CheckoutViewController.swift` in the sample app](https://github.com/stripe/stripe-ios/blob/1f8d56a1e5cdd02b48bf11808c1bf0dd7b3c7835/Example/Stripe%20iOS%20Example%20(Simple)/CheckoutViewController.swift#L146) to use `presentPaymentMethodsViewController` instead of `pushPaymentMethodsViewController`
2. Add a Card, then click "Payment" again to change to another card.  Here's a screenshot of what you'll see:
![Uploading Screen Shot 2017-01-04 at 12.48.17 PM.png…]()

So it appears the Cancel button works when presenting the `AddCardViewController`, but not when presenting the `PaymentMethodsViewController`.

I have a feeling it's related to this change: https://github.com/stripe/stripe-ios/commit/5e0c90e181f6bb5b80bc94bc968700b92e4b5b13#diff-070923c5585c916630e67c06d4127281L151

**Comment by bdorfman-stripe** [comment] 2017-01-04 21:44
Ah you are totally right, sorry for all the confusion. Fix is in https://github.com/stripe/stripe-ios/pull/529

**Comment by idris** [comment] 2017-01-04 21:45
No problem, thanks for the quick turnaround.

**Comment by bdorfman-stripe** [comment] 2017-01-05 21:27
Hopefully everything is working for you now in latest master. I'll also release a new version today or tomorrow. Let me know if you continue to have issues. Thanks again for the bug report!

**Closed by bdorfman-stripe** 2017-01-05 21:27 UTC
