### ISSUE TITLE
Stripe PaymentMethod ViewController Not localized in Swedish

### ISSUE THREAD

**Issue by unoiatech** [stripe/stripe-ios#915] opened 2018-04-05 09:48 UTC
I am trying to localize Stripe View Controllers in Swedish Language. 
I have added all the required strings in my app's localization file. Referred [this](https://github.com/stripe/stripe-ios/issues/657)

e.g.
/* Button to add a new credit card. */
"Add New Card…" = "LÄGG TILL BETALKORT";

But PaymentMethod ViewController still showing "Add New Card..."  in English.

**Comment by joeydong-stripe** [comment] 2018-04-05 17:12
Hi @unoiatech,

Can you clarify that the problem is "Add New Card..." is not translated using your localization strings but everything else is working fine? Maybe post a screenshot?

**Comment by joeydong-stripe** [comment] 2018-04-05 17:28
Since the SDK is not localized in Swedish as you've noticed, you can try installing the SDK using the "Dynamic Framework" option here: https://stripe.com/docs/mobile/ios. 

1. Download and unzip `Stripe.framework.zip`
2. Add your localization file to that `Stripe.framework` folder
3. Drag Stripe.framework to the "Embedded Binaries" section

**Comment by unoiatech** [comment] 2018-04-06 07:03
![img_2960](https://user-images.githubusercontent.com/17777840/38407181-19cdec7c-3996-11e8-9679-a2cf5196661d.png)


Here in the attached image, the screen is partially translated. Cancel(Avbryt) and done(klar) are in swedish language. 

But Add a Card is not translated even though I have translation added for this in app's localizable file.


Here is a screenshot from my localizable file 


![screen shot 2018-04-06 at 12 32 02 pm](https://user-images.githubusercontent.com/17777840/38407315-949b8c8e-3996-11e8-900e-a705e39993ac.png)

**Comment by joeydong-stripe** [comment] 2018-04-09 16:11
Hi @unoiatech, thanks for the screenshots. Looks like you need to add a translation for the string "Add a Card" (no ...). Does that work?

**Comment by Nailer** [comment] 2018-04-11 15:53
I have a question regarding localized languages, but I'm reluctant of making a new issue about it.

Is it possible for me to provide a Norwegian localization? I looked through the Localizable.strings file, and it seems like something I could translate in fifteen minutes.

**Comment by joeydong-stripe** [comment] 2018-04-11 16:00
@Nailer Oh yes! You can provide your own translations for any language we don't already translate for here: https://github.com/stripe/stripe-ios/tree/master/Stripe/Resources/Localizations

**Comment by Nailer** [comment] 2018-04-11 16:13
Without having to check the API right now, can I provide that localization without contributing to this repository, or should I make a pull request?

**Comment by joeydong-stripe** [comment] 2018-04-11 16:31
@Nailer  Absolutely, really appreciate it! Just post some translations for these strings and I'll do the legwork for getting it merged.

https://github.com/stripe/stripe-ios/blob/master/Stripe/Resources/Localizations/en.lproj/Localizable.strings

**Comment by Nailer** [comment] 2018-04-12 13:14
Did the legwork on this last night. Check out PR #921 .

**Comment by unoiatech** [comment] 2018-04-13 06:55
Thanks @joeydong-stripe  for response. I tried removing "..." but it doesn't seem to work. Also the string "Payment Method" does not have dots after it, this too is not translated.

**Comment by joeydong-stripe** [comment] 2018-04-13 18:16
@unoiatech Looking at this again, I believe "Cancel" and "Done" are translated because it's done by iOS by default and not because it's loaded from your localization file. Can you try adjusting the project settings for the localization file? For example, I would try disabling "Use Base Localization" and specifically creating a localization for Swedish.

**Closed** 2018-05-08 22:09 UTC
