### ISSUE TITLE
Unable to set Apple Pay as default Source when other cards are present.

### ISSUE THREAD

**Issue by calhouncole** [stripe/stripe-ios#1028] opened 2018-10-16 06:10 UTC
## Summary

After entering a credit card, I am no longer able to set Apple Pay as my default in the Payment Method View Controller. Because I cannot set it as my default, I must delete all cards before being able to use Apple Pay. 

In the 

## Code to reproduce

HostViewController.swift: 

    required init(coder aDecoder: NSCoder) {
        let config = STPPaymentConfiguration.shared()

        let customerContext = STPCustomerContext(keyProvider: StripeAPIClient.sharedClient)
        self.paymentContext = STPPaymentContext(customerContext: customerContext, configuration: config, theme: STPTheme.default())
        super.init(coder: aDecoder)!
        self.paymentContext.delegate = self
        self.paymentContext.hostViewController = self
    }

Later in the same View Controller:

`self.paymentContext.presentPaymentMethodsViewController()`

The following is called after I add a card or select "Apple Pay" as the default:

```
func paymentContextDidChange(_ paymentContext: STPPaymentContext) {
        print(paymentContext.selectedPaymentMethod)
        return
    }
```

The selected payment method that is printed does return an Apple Pay source after selecting apple pay. However, it doesn't seem that result.source.stripeID is being updated or saved, as it never returns the apple pay source unless it's the only card available.

## iOS version

ios 12

## Installation method

Cocoapods 

## SDK version

13.2.0

**Comment by edd677** [comment] 2018-10-16 06:42
I'm witnessing this too. Apple Pay is never set as the default payment method. If both a card and Apple Pay have been added, and Apple Pay is used, next launch it defaults to the last used card, not Apple Pay.

**Comment by calhouncole** [comment] 2018-10-16 19:51
In addition to that, it looks like it is saving a new card for every Apple Pay transaction? I'm assuming this isn't expected behavior?
![screenshot 2018-10-16 12 49 54](https://user-images.githubusercontent.com/5141235/47043298-2692c600-d142-11e8-9ad3-04ee310d02f2.png)

**Comment by aliriaz-stripe** [comment] 2018-10-16 23:21
Hi Cole, 
Thanks for writing in!

The STPPaymentContext will retain the customer's selected source between multiple push/present() calls to the same STPPaymentContext instance. 

However, if the app is relaunched or the STPPaymentContext is deallocated and created again, the STPCustomerContext will load your customer and their payment sources.
These sources are used to populate the payment methods on STPPaymentMethodsViewController and also show their default card.

The “Apple Pay” option in the STPPaymentMethodsViewController isn’t an instance of the user’s Apple Pay card but instead it indicates that the user would like to have the Apple Pay payment sheet UI presented to them when the `paymentContext.requestPayment()` method is called on the host view controller. This option is not the stored Apple Pay card for the user.

We understand that it might be more clear to display a "Pay with Apple Pay" button instead that fully integrates with STPPaymentContext. This could be a feature we might add in a future release, keep an eye out for it!

**Comment by aliriaz-stripe** [comment] 2018-10-26 21:03
Hi Cole,
Just circling back to your question about multiple cards, that is expected behavior. This is because you get a new card source every time an Apple Pay payment is authorized. This source is then added to the customer and charged.

If you have any more questions, you can write into https://support.stripe.com/email/login
Thanks!

**Comment by csabol-stripe** [comment] 2018-10-26 21:10
We are going to track adding new functionality to allow defaulting to ApplePay internally so closing this issue. Thank you!

**Closed by csabol-stripe** 2018-10-26 21:10 UTC

**Comment by siilats** [comment] 2019-05-06 21:24
Is this implemented?
